/*
 * convrot_int8_linear_kernel.cu — CUDA implementation of ConvRot + quant + epilogue.
 *
 * The INT8 GEMM is NOT in this file — it's handled by cuBLASLt in the plugin's
 * enqueue() method. This file only contains:
 *
 *   1. convrot_activation_quant_kernel — ConvRot rotation + per-row INT8 quant
 *   2. dequant_bias_epilogue_kernel — INT32 → FP32 dequant + bias add
 *
 * Ported from the ComfyUI-INT8-Fast Triton kernel (convrot.rotate_activation +
 * int8_fused_kernel._quantize_rowwise_kernel). The regular Hadamard matrix is
 * applied as H4 Kronecker butterflies, so the kernel does not need to stage a
 * dense group_size x group_size matrix in shared memory.
 */

#ifdef HOT_STEP_TRT

#include "convrot_int8_linear_kernel.cuh"

#include <cuda_runtime.h>
#include <cmath>
#include <cstdio>

namespace hotstep {

// ──────────────────────────────────────────────────────────────────────────
// ConvRot activation rotation + per-row INT8 quantization
// ──────────────────────────────────────────────────────────────────────────

template <int GROUP_SIZE>
__device__ __forceinline__ void regular_hadamard_transform(float* vals, float* tmp)
{
    int32_t tid = threadIdx.x;
    for (int32_t stride = 1; stride < GROUP_SIZE; stride *= 4) {
        int32_t span = stride * 4;
        int32_t combos = GROUP_SIZE / 4;
        for (int32_t c = tid; c < combos; c += blockDim.x) {
            int32_t base = (c / stride) * span + (c % stride);
            float x0 = vals[base];
            float x1 = vals[base + stride];
            float x2 = vals[base + 2 * stride];
            float x3 = vals[base + 3 * stride];
            tmp[base]              = 0.5f * ( x0 + x1 + x2 - x3);
            tmp[base + stride]     = 0.5f * ( x0 + x1 - x2 + x3);
            tmp[base + 2 * stride] = 0.5f * ( x0 - x1 + x2 + x3);
            tmp[base + 3 * stride] = 0.5f * (-x0 + x1 + x2 + x3);
        }
        __syncthreads();
        for (int32_t i = tid; i < GROUP_SIZE; i += blockDim.x) {
            vals[i] = tmp[i];
        }
        __syncthreads();
    }
}

template <int GROUP_SIZE, int BLOCK_K>
__global__ void convrot_activation_quant_kernel(
    float const* __restrict__ x_ptr,
    int8_t* __restrict__ x_q_ptr,
    float* __restrict__ x_scale_ptr,
    float const* __restrict__ H_ptr,
    int32_t M, int32_t K)
{
    (void)H_ptr;  // H is the same regular Hadamard generated by convrot.py.
    int32_t row = blockIdx.x;
    if (row >= M) return;
    int32_t tid = threadIdx.x;

    float const* x_row = x_ptr + (size_t)row * K;
    int8_t* xq_row = x_q_ptr + (size_t)row * K;

    extern __shared__ float smem[];
    float* s_x = smem;                       // [GROUP_SIZE]
    float* s_tmp = smem + GROUP_SIZE;        // [GROUP_SIZE]

    int32_t n_groups = K / GROUP_SIZE;
    float thread_max = 0.0f;

    // Phase 1: rotate each group and reduce max abs. We intentionally do not
    // store the full rotated row in shared memory; K is often 2048/6144.
    for (int32_t g = 0; g < n_groups; ++g) {
        int32_t base = g * GROUP_SIZE;
        for (int32_t i = tid; i < GROUP_SIZE; i += blockDim.x) {
            s_x[i] = x_row[base + i];
        }
        __syncthreads();

        regular_hadamard_transform<GROUP_SIZE>(s_x, s_tmp);
        for (int32_t i = tid; i < GROUP_SIZE; i += blockDim.x) {
            thread_max = fmaxf(thread_max, fabsf(s_x[i]));
        }
        __syncthreads();
    }

    // Tree reduce within the block
    __shared__ float s_reduce[32];
    int32_t lane = tid & 31;
    int32_t warp = tid >> 5;
    for (int32_t off = 16; off > 0; off >>= 1) {
        thread_max = fmaxf(thread_max, __shfl_xor_sync(0xffffffff, thread_max, off));
    }
    if (lane == 0) s_reduce[warp] = thread_max;
    __syncthreads();
    int32_t num_warps = (BLOCK_K + 31) / 32;
    if (warp == 0) {
        thread_max = (lane < num_warps) ? s_reduce[lane] : 0.0f;
        for (int32_t off = 16; off > 0; off >>= 1) {
            thread_max = fmaxf(thread_max, __shfl_xor_sync(0xffffffff, thread_max, off));
        }
        if (lane == 0) {
            float scale = fmaxf(thread_max / 127.0f, 1e-30f);
            x_scale_ptr[row] = scale;
            s_reduce[0] = scale;
        }
    }
    __syncthreads();
    float scale = s_reduce[0];

    // Phase 2: recompute the same rotation and quantize with the row scale.
    for (int32_t g = 0; g < n_groups; ++g) {
        int32_t base = g * GROUP_SIZE;
        for (int32_t i = tid; i < GROUP_SIZE; i += blockDim.x) {
            s_x[i] = x_row[base + i];
        }
        __syncthreads();

        regular_hadamard_transform<GROUP_SIZE>(s_x, s_tmp);
        for (int32_t i = tid; i < GROUP_SIZE; i += blockDim.x) {
            float v = s_x[i];
            float q = rintf(v / scale);
            q = fmaxf(-127.0f, fminf(127.0f, q));
            xq_row[base + i] = static_cast<int8_t>(q);
        }
        __syncthreads();
    }
}

// ──────────────────────────────────────────────────────────────────────────
// No-rotation activation quant (group_size == 0)
// ──────────────────────────────────────────────────────────────────────────
// Used when in_features % group_size != 0 — the ConvRot rotation is skipped
// and the activation is directly per-row INT8 quantized. Same quantization
// logic as the rotation kernel, just without the H-matrix rotation phase.

template <int BLOCK_K>
__global__ void activation_quant_norot_kernel(
    float const* __restrict__ x_ptr,
    int8_t* __restrict__ x_q_ptr,
    float* __restrict__ x_scale_ptr,
    int32_t M, int32_t K)
{
    int32_t row = blockIdx.x;
    if (row >= M) return;
    int32_t tid = threadIdx.x;

    float const* x_row = x_ptr + (size_t)row * K;
    int8_t* xq_row = x_q_ptr + (size_t)row * K;

    // Phase 1: per-row max-abs reduction (tiled over K).
    float thread_max = 0.0f;
    for (int32_t tile = 0; tile < K; tile += BLOCK_K) {
        for (int32_t i = tid; i < BLOCK_K && tile + i < K; i += BLOCK_K) {
            float v = fabsf(x_row[tile + i]);
            thread_max = fmaxf(thread_max, v);
        }
    }

    // Tree reduce within the block
    __shared__ float s_reduce[32];
    int32_t lane = tid & 31;
    int32_t warp = tid >> 5;
    for (int32_t off = 16; off > 0; off >>= 1) {
        thread_max = fmaxf(thread_max, __shfl_xor_sync(0xffffffff, thread_max, off));
    }
    if (lane == 0) s_reduce[warp] = thread_max;
    __syncthreads();
    int32_t num_warps = (BLOCK_K + 31) / 32;
    if (warp == 0) {
        thread_max = (lane < num_warps) ? s_reduce[lane] : 0.0f;
        for (int32_t off = 16; off > 0; off >>= 1) {
            thread_max = fmaxf(thread_max, __shfl_xor_sync(0xffffffff, thread_max, off));
        }
        if (lane == 0) {
            float scale = fmaxf(thread_max / 127.0f, 1e-30f);
            x_scale_ptr[row] = scale;
            s_reduce[0] = scale;
        }
    }
    __syncthreads();
    float scale = s_reduce[0];

    // Phase 2: quantize and store.
    for (int32_t tile = 0; tile < K; tile += BLOCK_K) {
        for (int32_t i = tid; i < BLOCK_K && tile + i < K; i += BLOCK_K) {
            float v = x_row[tile + i];
            float q = rintf(v / scale);
            q = fmaxf(-127.0f, fminf(127.0f, q));
            xq_row[tile + i] = static_cast<int8_t>(q);
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────
// Dequant + bias epilogue (applied to cuBLASLt INT32 output)
// ──────────────────────────────────────────────────────────────────────────

template <int BLOCK_M, int BLOCK_N, bool HAS_BIAS>
__global__ void dequant_bias_epilogue_kernel(
    int32_t const* __restrict__ acc_ptr,
    float* __restrict__ y_ptr,
    float const* __restrict__ x_scale,
    float const* __restrict__ w_scale,
    float const* __restrict__ bias_ptr,
    int32_t M, int32_t N)
{
    int32_t bm = blockIdx.x * BLOCK_M;
    int32_t bn = blockIdx.y * BLOCK_N;
    int32_t tm = threadIdx.x;
    int32_t tn = threadIdx.y;

    int32_t m = bm + tm;
    int32_t n = bn + tn;
    if (m >= M || n >= N) return;

    int32_t acc = acc_ptr[m * N + n];
    float xs = x_scale[m];
    float ws = w_scale[n];
    float v = static_cast<float>(acc) * xs * ws;
    if (HAS_BIAS) {
        v += bias_ptr[n];
    }
    y_ptr[m * N + n] = v;
}

// ──────────────────────────────────────────────────────────────────────────
// Launch helpers
// ──────────────────────────────────────────────────────────────────────────

bool launch_convrot_activation_quant(
    float const* x, int8_t* x_q, float* x_scale, float const* H,
    int32_t M, int32_t K, int32_t group_size, cudaStream_t stream)
{
    if (group_size == 0) {
        // No ConvRot rotation — just per-row INT8 quantization. Used when
        // in_features % group_size != 0 (the rotation can't be applied).
        // The H pointer is ignored.
        int32_t block_k = 256;
        dim3 grid(M);
        dim3 block(block_k);
        int32_t smem_bytes = block_k * sizeof(float);
        activation_quant_norot_kernel<256>
            <<<grid, block, smem_bytes, stream>>>(x, x_q, x_scale, M, K);
        return cudaGetLastError() == cudaSuccess;
    }
    if (K % group_size != 0) return false;

    int32_t block_k = 256;
    int32_t smem_bytes = 2 * group_size * sizeof(float);

    dim3 grid(M);
    dim3 block(block_k);
    switch (group_size) {
        case 4:
            convrot_activation_quant_kernel<4, 256>
                <<<grid, block, smem_bytes, stream>>>(x, x_q, x_scale, H, M, K);
            break;
        case 16:
            convrot_activation_quant_kernel<16, 256>
                <<<grid, block, smem_bytes, stream>>>(x, x_q, x_scale, H, M, K);
            break;
        case 64:
            convrot_activation_quant_kernel<64, 256>
                <<<grid, block, smem_bytes, stream>>>(x, x_q, x_scale, H, M, K);
            break;
        case 256:
            convrot_activation_quant_kernel<256, 256>
                <<<grid, block, smem_bytes, stream>>>(x, x_q, x_scale, H, M, K);
            break;
        case 1024:
            convrot_activation_quant_kernel<1024, 256>
                <<<grid, block, smem_bytes, stream>>>(x, x_q, x_scale, H, M, K);
            break;
        default:
            return false;
    }
    return cudaGetLastError() == cudaSuccess;
}

bool launch_dequant_bias_epilogue(
    int32_t const* acc, float* y,
    float const* x_scale, float const* w_scale, float const* bias,
    int32_t M, int32_t N, bool has_bias, cudaStream_t stream)
{
    constexpr int BLOCK_M = 16;
    constexpr int BLOCK_N = 16;
    dim3 grid((M + BLOCK_M - 1) / BLOCK_M, (N + BLOCK_N - 1) / BLOCK_N);
    dim3 block(BLOCK_M, BLOCK_N);

    if (has_bias) {
        dequant_bias_epilogue_kernel<BLOCK_M, BLOCK_N, true>
            <<<grid, block, 0, stream>>>(acc, y, x_scale, w_scale, bias, M, N);
    } else {
        dequant_bias_epilogue_kernel<BLOCK_M, BLOCK_N, false>
            <<<grid, block, 0, stream>>>(acc, y, x_scale, w_scale, bias, M, N);
    }
    return cudaGetLastError() == cudaSuccess;
}

}  // namespace hotstep

#endif  // HOT_STEP_TRT
