/*
 * convrot_int8_linear_plugin.cpp — IPluginV3 implementation for ConvRotInt8Linear.
 *
 * Phase 1 architecture — fully-fused Triton AOT kernel via CUDA Driver API:
 *
 *   enqueue() pipeline (single Triton kernel launch):
 *     1. ConvRot activation rotation via in-register H_4 Kronecker butterfly
 *     2. Per-row dynamic INT8 quantization
 *     3. INT8 × INT8 → INT32 GEMM via Tensor Cores (tl.dot)
 *     4. Dequant + bias + FP16 cast epilogue
 *
 * Rotation design (butterfly, NOT H-matrix matmul):
 *   The Hadamard rotation H_{GROUP_SIZE} is decomposed into log_4(GROUP_SIZE)
 *   successive H_4 butterfly stages, all performed in registers. This avoids
 *   materializing the full [GROUP_SIZE × GROUP_SIZE] H matrix in shared memory
 *   (which would be 128 KB for GROUP_SIZE=256 in FP16 — exceeding the sm_86
 *   99 KB hardware limit and causing cuLaunchKernel to fail with
 *   CUDA_ERROR_INVALID_VALUE). The butterfly approach works uniformly for all
 *   valid group sizes {4, 16, 64, 256, 1024} and uses zero shared memory for
 *   rotation. Fusion is preserved — all butterfly ops are elementwise on
 *   register tiles.
 *
 * Cubin dispatch:
 *   At onShapeChange(), the plugin loads the AOT-compiled cubin matching the
 *   runtime (tactic, group_size, has_bias) tuple via cuModuleLoadData. Cubin
 *   names follow the pattern kCONVROT_INT8_KERNEL_{TILE}_G{GROUP}_{BIAS|NOBIAS}.
 *   The cubins are generated by tools/onnx-export/compile_triton_plugin.py and
 *   embedded in engine/src/plugins/assets/convrot_int8_kernel_cubin.h.
 *
 * Shared-memory opt-in:
 *   Triton GEMM kernels with multi-stage pipelining bake >48 KB of static
 *   shared memory into the cubin. We query the static shared-mem size via
 *   cuFuncGetAttribute and opt in to the larger per-block carveout via
 *   cuFuncSetAttribute(MAX_DYNAMIC_SHARED_SIZE_BYTES) before launch. Without
 *   this opt-in, cuLaunchKernel returns CUDA_ERROR_INVALID_VALUE.
 *
 * Build vs Runtime:
 *   - Build: TRT calls configurePlugin() + getWorkspaceSize() (returns 0).
 *   - Runtime: onShapeChange() loads cubin + opts in to shared mem;
 *     enqueue() launches the fused kernel.
 */

#ifdef HOT_STEP_TRT

#include "convrot_int8_linear_plugin.h"
#include "convrot_int8_linear_kernel.cuh"

#include <cuda.h>
#include "assets/convrot_int8_kernel_cubin.h"
#include <cuda_runtime.h>

// ── Cubin header version guard ─────────────────────────────────────────────
// The cubin header must declare CONVROT_INT8_CUBIN_HEADER_VERSION >= 3 to
// carry the per-cubin kCONVROT_INT8_KERNEL_*_BLOCK_M / _BLOCK_N constants
// that this plugin reads at runtime (in addition to the _SHARED constants
// introduced in v2). Version < 3 means the header was generated by an older
// compile script that did NOT emit per-cubin tile dimensions, so the plugin
// would use stale hardcoded BLOCK_M=128 for grid calculation — producing
// wrong grid sizes for G256 FP32IO cubins (which use BLOCK_M=64).
//
// Version 1: original (no _SHARED, no _BLOCK_M/_BLOCK_N)
// Version 2: added _SHARED constants (shared-mem pre-flight check)
// Version 3: added _BLOCK_M / _BLOCK_N (per-cubin tile selection)
#ifndef CONVROT_INT8_CUBIN_HEADER_VERSION
#  error "Cubin header is missing CONVROT_INT8_CUBIN_HEADER_VERSION. Re-run tools/onnx-export/compile_triton_plugin_sm86.py to regenerate engine/src/plugins/assets/convrot_int8_kernel_cubin.h."
#elif CONVROT_INT8_CUBIN_HEADER_VERSION < 3
#  error "Cubin header version >= 3 required (with _BLOCK_M/_BLOCK_N constants). Re-run tools/onnx-export/compile_triton_plugin_sm86.py to regenerate engine/src/plugins/assets/convrot_int8_kernel_cubin.h."
#endif
#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <fstream>
#include <limits>
#include <mutex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <utility>

#if defined(_WIN32)
#  define WIN32_LEAN_AND_MEAN 1
#  define NOMINMAX 1
#  include <windows.h>  // OutputDebugStringW, MultiByteToWideChar
#endif

namespace hotstep {

// ── Diagnostic logging ──────────────────────────────────────────────────────
//
// Compile-time gating: the entire diag subsystem is compiled in ONLY when
// HOTSTEP_PLUGIN_DEBUG is defined at build time (e.g. via
//   cmake -DHOTSTEP_PLUGIN_DEBUG=1 ...
// or by adding `target_compile_definitions(hotstep_plugins PRIVATE HOTSTEP_PLUGIN_DEBUG)`
// to CMakeLists.txt for debug builds).
//
// When HOTSTEP_PLUGIN_DEBUG is NOT defined, log() and flush() are inline
// no-ops. The compiler eliminates the call site entirely — including
// argument evaluation — so there is ZERO runtime overhead from the dozens of
// log calls scattered through onShapeChange() / enqueue() / initTriton().
// This is critical for production throughput: the DiT inference loop calls
// these methods 359 times per step, and even ~100ns of per-call overhead
// from runtime env-var checks would add up to ~36us per step (negligible
// here, but the principle matters for hot paths).
//
// When HOTSTEP_PLUGIN_DEBUG IS defined, the full RAM-buffered logging
// subsystem is compiled in, with runtime control via the HOTSTEP_PLUGIN_DEBUG
// environment variable (set to "1", "immediate", or "stdout"). See the
// long comment below for details.
//
// TRT 11's PluginV3Runner::execute assertion at line 252 fires whenever any
// plugin method returns non-success. TRT swallows plugin stderr, leaving the
// user with only the bare assertion. To work around this, when diagnostics
// are enabled, every message is written to a RAM buffer with three sinks:
//
//   1. A RAM buffer (fast — pure memcpy under mutex, ~100ns/call)
//   2. stderr (cheap, may be swallowed by TRT)
//   3. OutputDebugStringW on Windows (kernel call, ~1us, always visible in VS)
//
// The RAM buffer is flushed to disk (hotstep_plugin_diag.log) only when:
//   - The buffer crosses kFlushThreshold (default 1 MB)
//   - An error-path message is logged (contains FAILURE/REJECT/failed)
//   - The DLL is unloaded (static destructor)
//
// This keeps per-call cost at ~5-10us (mostly OutputDebugStringW) instead of
// the ~500us of file I/O per call. For a DiT inference pass with ~100 plugin
// invocations, that's ~1ms total overhead — negligible.
//
// Performance gating:
//   Diagnostics are OFF by default — zero overhead. Enable by setting
//   HOTSTEP_PLUGIN_DEBUG=1 in the environment before loading the plugin DLL.
//   The enabled() check is a single atomic bool read (~1ns).
//
//   Set HOTSTEP_PLUGIN_DEBUG=immediate to force a disk flush on EVERY log
//   call — useful for debugging crashes that prevent the static destructor
//   from running (e.g., TRT assertion aborts before DLL unload).
namespace diag {

#ifdef HOTSTEP_PLUGIN_DEBUG
// ──────────────────────────────────────────────────────────────────────────
// Full diagnostic logging implementation (compiled only when
// HOTSTEP_PLUGIN_DEBUG is defined at build time).
// ──────────────────────────────────────────────────────────────────────────

constexpr size_t kFlushThreshold = 1ull * 1024ull * 1024ull;  // 1 MB

std::mutex& logMutex() {
    static std::mutex m;
    return m;
}

std::string logPath() {
    char const* env = std::getenv("HOTSTEP_PLUGIN_LOG");
    if (env && env[0] != '\0') return std::string(env);
    // Default: hotstep_plugin_diag.log in the host process's CWD.
    // Set HOTSTEP_PLUGIN_LOG to redirect (e.g., to share the host's main log
    // by pointing this at the same path the host process logs to).
    return std::string("hotstep_plugin_diag.log");
}

// If true, also emit every log line to stdout (not just stderr). Useful when
// the host process redirects stdout to its main log file — plugin diagnostics
// will then be co-located with the rest of the application's output.
// Enable with HOTSTEP_PLUGIN_DEBUG=stdout  (implies enabled() too).
bool echoToStdout() {
    static bool cached = false;
    static std::once_flag flag;
    std::call_once(flag, []() {
        char const* env = std::getenv("HOTSTEP_PLUGIN_DEBUG");
        cached = (env != nullptr && std::strcmp(env, "stdout") == 0);
    });
    return cached;
}

bool enabled() {
    static bool cached = false;
    static std::once_flag flag;
    std::call_once(flag, []() {
        char const* env = std::getenv("HOTSTEP_PLUGIN_DEBUG");
        // Any non-empty value except "0" enables diagnostics. The special
        // values "immediate" and "stdout" select extra modes (immediate:
        // per-call disk flush; stdout: also echo to stdout).
        cached = (env != nullptr && env[0] != '\0' && env[0] != '0');
    });
    return cached;
}

// "immediate" mode: flush to disk after every log call. Useful when the
// process might crash before the static destructor runs.
bool immediateMode() {
    static bool cached = false;
    static std::once_flag flag;
    std::call_once(flag, []() {
        char const* env = std::getenv("HOTSTEP_PLUGIN_DEBUG");
        cached = (env != nullptr && std::strcmp(env, "immediate") == 0);
    });
    return cached;
}

// RAM buffer — pre-allocated to 256 KB, grows as needed. Lives for the DLL's
// lifetime. All log calls append to this; flushes to disk are batched.
std::string& logBuffer() {
    static std::string buf;
    static std::once_flag flag;
    std::call_once(flag, []() {
        try { buf.reserve(256 * 1024); } catch (...) {}
    });
    return buf;
}

// Persistent log file stream — opened lazily on first flush, kept open.
std::ofstream& logStream() {
    static std::ofstream f;
    static std::once_flag flag;
    std::call_once(flag, []() {
        try { f.open(logPath(), std::ios::app); } catch (...) {}
    });
    return f;
}

// Internal: flush RAM buffer to disk. Caller MUST hold logMutex().
void flushToDiskLocked() {
    std::string& buf = logBuffer();
    if (buf.empty()) return;
    try {
        std::ofstream& f = logStream();
        if (f.is_open()) {
            f.write(buf.data(), static_cast<std::streamsize>(buf.size()));
            f.flush();
        }
    } catch (...) {
        // Swallow — logging must never throw.
    }
    buf.clear();
}

// Quick scan of a formatted message to decide whether to force a flush.
// Error-path messages (FAILURE/REJECT/failed) should reach disk immediately
// so they survive a process crash.
bool isErrorPath(char const* msg) {
    return std::strstr(msg, "FAILURE") != nullptr ||
           std::strstr(msg, "REJECT")  != nullptr ||
           std::strstr(msg, "failed")  != nullptr ||
           std::strstr(msg, "BUILD-TIME") != nullptr;
}

void log(char const* fmt, ...) {
    if (!enabled()) return;

    // 1. Format into stack buffer (no lock needed).
    char buf[2048];
    int len = 0;

    std::time_t now = std::time(nullptr);
    char ts[32];
    std::strftime(ts, sizeof(ts), "%Y-%m-%d %H:%M:%S", std::gmtime(&now));
    len += std::snprintf(buf + len, sizeof(buf) - len, "[HotStep %s] ", ts);

    va_list args;
    va_start(args, fmt);
    len += std::vsnprintf(buf + len, sizeof(buf) - len, fmt, args);
    va_end(args);

    if (len > 0 && buf[len - 1] != '\n') {
        if (len < (int)sizeof(buf) - 1) {
            buf[len++] = '\n';
            buf[len] = '\0';
        }
    }

    bool const force_flush = isErrorPath(buf) || immediateMode();

    // 2. Append to RAM buffer + optionally flush, all under one mutex hold.
    bool need_flush = false;
    {
        std::lock_guard<std::mutex> lock(logMutex());

        // Append to RAM buffer (fast — string::append is amortized memcpy).
        try {
            logBuffer().append(buf, static_cast<size_t>(len));
        } catch (...) {
            // Swallow — logging must never throw.
        }

        if (force_flush || logBuffer().size() >= kFlushThreshold) {
            need_flush = true;
        }
    }

    // 3. stderr — cheap, may be swallowed by TRT.
    std::fputs(buf, stderr);
    std::fflush(stderr);

    // 3b. stdout — only in "stdout" mode. Use this when the host process
    //     redirects stdout to its main log file: plugin diagnostics will be
    //     co-located with the rest of the application's output, in order.
    if (echoToStdout()) {
        std::fputs(buf, stdout);
        std::fflush(stdout);
    }

    // 4. Windows debugger — cheap kernel call (~1us), always visible.
#if defined(_WIN32)
    int wlen = MultiByteToWideChar(CP_UTF8, 0, buf, -1, nullptr, 0);
    if (wlen > 0) {
        std::wstring wbuf(static_cast<size_t>(wlen), L'\0');
        MultiByteToWideChar(CP_UTF8, 0, buf, -1, &wbuf[0], wlen);
        OutputDebugStringW(wbuf.c_str());
    }
#endif

    // 5. Flush to disk if threshold crossed, error path, or immediate mode.
    //    Done OUTSIDE the mutex-held section above only conceptually — we
    //    re-acquire the mutex here. This is fine because the work inside is
    //    just file I/O which is rare (once per 1MB or once per error).
    if (need_flush) {
        std::lock_guard<std::mutex> lock(logMutex());
        flushToDiskLocked();
    }
}

// Public flush API — exposed so callers can force a flush on demand (e.g.,
// from a signal handler or before a deliberate abort).
void flush() {
    if (!enabled()) return;
    std::lock_guard<std::mutex> lock(logMutex());
    flushToDiskLocked();
}

// Static destructor — flushes the RAM buffer to disk at DLL unload. Ensures
// the last few KB of buffered messages (below kFlushThreshold) are not lost.
//
// STATIC DESTRUCTION ORDER: g_buffer_flusher is a namespace-scope static,
// constructed at DLL load. logBuffer()/logStream()/logMutex() are function-
// local statics, constructed on first log() call (which happens AFTER DLL
// load, during the first plugin method). So the destruction order is:
//   1. logStream(), logBuffer(), logMutex() destroyed (function-local, LIFO)
//   2. g_buffer_flusher destroyed (namespace-scope)
//
// This means g_buffer_flusher's destructor would access DEAD logStream()/
// logBuffer()/logMutex() objects — a use-after-free. To avoid this, the
// destructor does NOTHING. The RAM buffer is flushed incrementally during
// normal operation (on error paths, on 1 MB threshold, or in immediate mode),
// so the only data lost is the last few KB of buffered messages below the
// threshold — acceptable for a debug-only diagnostic log.
struct BufferFlusher {
    ~BufferFlusher() {
        // Intentionally empty — see comment above. Doing file I/O in a static
        // destructor is unsafe because function-local statics (logStream,
        // logBuffer, logMutex) may already be destroyed.
    }
};
BufferFlusher g_buffer_flusher;

#else  // !HOTSTEP_PLUGIN_DEBUG
// ──────────────────────────────────────────────────────────────────────────
// No-op stubs (compiled when HOTSTEP_PLUGIN_DEBUG is NOT defined).
//
// These are inline functions with empty bodies. Any modern compiler at -O1 or
// higher will eliminate the call site entirely, including all argument
// evaluation (since the arguments are unused and the functions have no side
// effects). This gives ZERO runtime overhead for production builds.
//
// logPath() returns an empty string — it's only used as an argument to log(),
// which is itself a no-op, so the return value is never observed. The stub
// exists solely so the symbol resolves at compile time (MSVC does name lookup
// before dead-code elimination, so even unused arguments must reference
// declared symbols).
// ──────────────────────────────────────────────────────────────────────────

inline void log(char const* /*fmt*/, ...) noexcept {}
inline void flush() noexcept {}
inline std::string logPath() noexcept { return std::string{}; }

#endif  // HOTSTEP_PLUGIN_DEBUG

}  // namespace diag

namespace {

unsigned int getDeviceMaxDynamicSharedMem() {
    static unsigned int cached = 0;
    static std::once_flag flag;
    std::call_once(flag, []() {
        int dev = 0;
        cudaGetDevice(&dev);
        cudaDeviceProp prop{};
        cudaGetDeviceProperties(&prop, dev);
        cached = static_cast<unsigned int>(prop.sharedMemPerBlockOptin);
        if (cached == 0) cached = 48 * 1024; // fallback
    });
    return cached;
}

// ── Global CUmodule cache ──────────────────────────────────────────────────
//
// PROBLEM: TRT 11's IPluginV3 lifecycle calls attachToContext() → clone() for
// EACH plugin instance at EACH inference step. The clone() method creates a
// new plugin with m_module = nullptr. When onShapeChange() runs on the cloned
// instance, it calls initTriton() → cuModuleLoadData(), which parses a ~2 MB
// ELF cubin and loads the SASS into GPU memory. With 359 ConvRotInt8Linear
// instances in the DiT engine, that's 359 cuModuleLoadData calls per step,
// each taking ~100–400 ms — totaling 36–144 s per step. This is the dominant
// overhead in the DiT inference loop (150 s/step observed vs. <2 s/step with
// the old cuBLASLt path).
//
// SOLUTION: Cache the loaded CUmodule globally, keyed by the cubin data
// pointer. The cubin data is a `constexpr unsigned char[]` array in .rodata,
// so its address is stable for the DLL's lifetime. Multiple plugin instances
// with the same (group_size, has_bias, dtype, M==1?) config share the same
// CUmodule and CUfunction. The cache is:
//   - Thread-safe (guarded by a mutex, but only held during lookup/insert —
//     never during kernel execution).
//   - Lazy (modules are loaded on first use, not at DLL load).
//   - Leaked at process exit (NOT cleaned up by a static destructor — see
//     the comment above moduleCache() for why static destructor cleanup
//     causes access violations). The CUDA driver reclaims all GPU memory
//     when the process exits.
//
// With this cache, the first DiT step loads 4 unique cubins (2 × 128x128
// for G256 FP32IO BIAS/NOBIAS + 2 × M1 for G256 FP32IO BIAS/NOBIAS).
// Subsequent steps hit the cache — zero cuModuleLoadData calls, zero
// cuModuleGetFunction calls, zero cuFuncSetAttribute calls. initTriton()
// becomes a single mutex + hash lookup (~200 ns).
//
// The cache key is the raw cubin data pointer (void const*). This is safe
// because:
//   1. All cubins are constexpr arrays in the cubin header — their addresses
//      are fixed for the DLL's lifetime.
//   2. Two plugins with the same config call selectCubin()/selectM1Cubin()
//      which return the SAME constexpr array pointer.
//   3. The pointer is never dereferenced after the lookup — we only use it
//      as a hash key.
struct CachedModule {
    CUmodule module;
    CUfunction func;
    size_t shared_bytes;
    int block_m;
    int block_n;
};

std::mutex& moduleCacheMutex() {
    static std::mutex m;
    return m;
}

std::unordered_map<void const*, CachedModule>& moduleCache() {
    static std::unordered_map<void const*, CachedModule> cache;
    return cache;
}

// NOTE: We intentionally do NOT unload cached CUmodules at DLL unload / process
// exit. Attempting cuModuleUnload() in a static destructor causes an access
// violation (0xC0000005) on Windows because:
//
//   1. TRT's own teardown runs first and destroys the CUDA context it created.
//      Calling cuModuleUnload() after the context is gone is undefined behavior
//      and crashes with an access violation.
//   2. Static destruction order: moduleCache() is a function-local static
//      (constructed on first cache miss), while any namespace-scope cleaner
//      would construct at DLL load — meaning the cleaner destructs AFTER the
//      map, accessing a dead object (another use-after-free).
//
// Leaking CUmodule handles during process exit is completely harmless: the
// CUDA driver reclaims all GPU memory when the process exits. The total leak
// is ~4 unique cubins × a few KB of driver-side metadata = negligible.
//
// If DLL hot-reload (unload without process exit) is ever needed, the cleanup
// must be done via an explicit teardown function called BEFORE TRT destroys
// its context — never via a static destructor.

constexpr size_t kCUBLASLT_WORKSPACE_BYTES = 32ull * 1024ull * 1024ull;

size_t alignUp(size_t value, size_t alignment) {
    return (value + alignment - 1) / alignment * alignment;
}

char* alignPtr(char* ptr, size_t alignment) {
    uintptr_t raw = reinterpret_cast<uintptr_t>(ptr);
    raw = (raw + alignment - 1) & ~(static_cast<uintptr_t>(alignment) - 1);
    return reinterpret_cast<char*>(raw);
}

int64_t flattenedRows(nvinfer1::Dims const& dims) {
    if (dims.nbDims < 1) return 0;
    int64_t rows = 1;
    for (int32_t i = 0; i < dims.nbDims - 1; ++i) {
        if (dims.d[i] <= 0) return 0;
        rows *= dims.d[i];
    }
    return rows;
}

int32_t lastDim(nvinfer1::Dims const& dims) {
    if (dims.nbDims < 1) return 0;
    return dims.d[dims.nbDims - 1];
}

int32_t normalizeDtypeId(int32_t value, int32_t defaultValue = 10) {
    // ONNX TensorProto enum: FLOAT=1, FLOAT16=10, BFLOAT16=16.
    if (value == 1 || value == 10 || value == 16) return value;
    return defaultValue;
}

int32_t parseDtypeId(char const* value, int32_t defaultValue = 10) {
    if (value == nullptr || value[0] == '\0') return defaultValue;
    std::string s(value);
    for (char& c : s) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    if (s == "FP16" || s == "FLOAT16" || s == "HALF") return 10;
    if (s == "BF16" || s == "BFLOAT16") return 16;
    if (s == "FP32" || s == "FLOAT" || s == "FLOAT32") return 1;
    return defaultValue;
}

nvinfer1::DataType trtTypeFromDtypeId(int32_t dtypeId) {
    if (dtypeId == 10) return nvinfer1::DataType::kHALF;
    if (dtypeId == 16) return nvinfer1::DataType::kBF16;
    return nvinfer1::DataType::kFLOAT;
}

int32_t kernelDtypeFromTrt(nvinfer1::DataType dtype) {
    if (dtype == nvinfer1::DataType::kHALF) return 1;
    if (dtype == nvinfer1::DataType::kBF16) return 2;
    return 0;
}

char const* dtypeNameFromId(int32_t dtypeId) {
    if (dtypeId == 10) return "FP16";
    if (dtypeId == 16) return "BF16";
    return "FP32";
}

bool readPluginString(nvinfer1::PluginField const& f, char* dst, size_t dstSize) {
    if (dst == nullptr || dstSize == 0) return false;
    dst[0] = '\0';
    if (f.data == nullptr || f.length <= 0) return false;
    auto const* src = static_cast<char const*>(f.data);
    size_t maxLen = static_cast<size_t>(f.length);
    size_t n = 0;
    while (n < maxLen && src[n] != '\0') ++n;
    n = std::min(n, dstSize - 1);
    std::memcpy(dst, src, n);
    dst[n] = '\0';
    return true;
}

bool validGroupSize(int32_t groupSize, int32_t K) {
    if (groupSize == 0) return true;
    switch (groupSize) {
        case 4:
        case 16:
        case 64:
        case 256:
        case 1024:
            return K > 0 && K % groupSize == 0;
        default:
            return false;
    }
}

size_t pluginWorkspaceBytes(int64_t M, int64_t K, int64_t N) {
    if (M <= 0 || K <= 0 || N <= 0) return 0;
    // Runtime aligns the workspace pointer itself; reserve worst-case headroom
    // so those alignment bumps never exceed TensorRT's requested size.
    size_t cursor = 256;
    cursor = alignUp(cursor, 16);
    cursor += static_cast<size_t>(M) * static_cast<size_t>(K) * sizeof(int8_t);
    cursor = alignUp(cursor, 16);
    cursor += static_cast<size_t>(M) * sizeof(float);
    cursor = alignUp(cursor, 256);
    cursor += static_cast<size_t>(M) * static_cast<size_t>(N) * sizeof(int32_t);
    cursor = alignUp(cursor, 256);
    cursor += kCUBLASLT_WORKSPACE_BYTES;
    return cursor;
}

}  // namespace

// ──────────────────────────────────────────────────────────────────────────
// ConvRotInt8LinearPlugin
// ──────────────────────────────────────────────────────────────────────────

ConvRotInt8LinearPlugin::ConvRotInt8LinearPlugin(
    int32_t group_size, int32_t in_features, int32_t out_features, int32_t has_bias,
    int32_t input_dtype_id, int32_t output_dtype_id, std::string preferred_format)
    : m_group_size(group_size),
      m_in_features(in_features),
      m_out_features(out_features),
      m_has_bias(has_bias),
      m_input_dtype_id(normalizeDtypeId(input_dtype_id)),
      m_output_dtype_id(normalizeDtypeId(output_dtype_id)),
      m_preferred_format(std::move(preferred_format)) {}

ConvRotInt8LinearPlugin::ConvRotInt8LinearPlugin(void const* data, size_t length) {
    if (length != getSerializationSize()) return;
    uint8_t const* d = static_cast<uint8_t const*>(data);
    int32_t input_dtype_id = 10, output_dtype_id = 10;
    std::memcpy(&m_group_size,   d, sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(&m_in_features,  d, sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(&m_out_features, d, sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(&m_has_bias,     d, sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(&input_dtype_id,  d, sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(&output_dtype_id, d, sizeof(int32_t)); d += sizeof(int32_t);
    m_input_dtype_id = normalizeDtypeId(input_dtype_id);
    m_output_dtype_id = normalizeDtypeId(output_dtype_id);
}

ConvRotInt8LinearPlugin::~ConvRotInt8LinearPlugin() {
    destroyTriton();
}

// ── IPluginV3 ──────────────────────────────────────────────────────────────

nvinfer1::IPluginCapability* ConvRotInt8LinearPlugin::getCapabilityInterface(
    nvinfer1::PluginCapabilityType type) noexcept {
    if (type == nvinfer1::PluginCapabilityType::kBUILD)
        return static_cast<nvinfer1::IPluginV3OneBuild*>(this);
    if (type == nvinfer1::PluginCapabilityType::kRUNTIME)
        return static_cast<nvinfer1::IPluginV3OneRuntime*>(this);
    return static_cast<nvinfer1::IPluginV3OneCore*>(this);
}

// ── IPluginV3OneCore ──────────────────────────────────────────────────────

char const* ConvRotInt8LinearPlugin::getPluginName() const noexcept {
    return kCONVROT_INT8_LINEAR_PLUGIN_NAME;
}
char const* ConvRotInt8LinearPlugin::getPluginVersion() const noexcept {
    return kCONVROT_INT8_LINEAR_PLUGIN_VERSION;
}
char const* ConvRotInt8LinearPlugin::getPluginNamespace() const noexcept {
    return m_namespace.c_str();
}
// Note: setPluginNamespace() removed in TRT 11; namespace is set via creator.

// ── IPluginV3OneBuild ──────────────────────────────────────────────────────

int32_t ConvRotInt8LinearPlugin::getNbOutputs() const noexcept { return 1; }

int32_t ConvRotInt8LinearPlugin::getOutputDataTypes(
    nvinfer1::DataType* outputTypes, int32_t nbOutputs,
    nvinfer1::DataType const*, int32_t) const noexcept {
    if (nbOutputs < 1) return -1;
    outputTypes[0] = trtTypeFromDtypeId(m_output_dtype_id);
    return 0;
}

int32_t ConvRotInt8LinearPlugin::getOutputShapes(
    nvinfer1::DimsExprs const* inputs, int32_t nbInputs,
    nvinfer1::DimsExprs const*, int32_t,
    nvinfer1::DimsExprs* outputs, int32_t nbOutputs,
    nvinfer1::IExprBuilder& exprBuilder) noexcept {
    if (nbOutputs < 1 || nbInputs < 1) return -1;
    auto const& x_dims = inputs[0];
    int32_t ndim = x_dims.nbDims;
    if (ndim < 1) return -1;
    outputs[0].nbDims = ndim;
    for (int32_t i = 0; i < ndim - 1; ++i)
        outputs[0].d[i] = x_dims.d[i];
    outputs[0].d[ndim - 1] = exprBuilder.constant(m_out_features);
    return 0;
}

bool ConvRotInt8LinearPlugin::supportsFormatCombination(
    int32_t pos, nvinfer1::DynamicPluginTensorDesc const* inOut,
    int32_t nbInputs, int32_t nbOutputs) noexcept {
    if (pos < 0 || pos >= nbInputs + nbOutputs) return false;

    // The current kernel indexes tensors as contiguous row-major memory. Keep
    // kLINEAR as the only accepted physical layout until the packed-layout
    // kernels land; the v2 dtype/tactic contract is independent of that future
    // optimization. The ONNX-side preferred_format attribute is still parsed
    // and serialized so future kernels can enable packed formats without graph
    // changes.
    if (inOut[pos].desc.format != nvinfer1::PluginFormat::kLINEAR) return false;

    auto type = inOut[pos].desc.type;
    auto inputType = trtTypeFromDtypeId(m_input_dtype_id);
    auto outputType = trtTypeFromDtypeId(m_output_dtype_id);
    if (pos < nbInputs) {
        switch (pos) {
            case 0: return type == inputType;                        // x
            case 1: return type == nvinfer1::DataType::kINT8;        // weight_q
            case 2: return type == nvinfer1::DataType::kFLOAT;       // weight_scale
            case 3: return m_has_bias && type == nvinfer1::DataType::kFLOAT; // bias stays FP32 (1D sane rule)
            default: return false;
        }
    }
    return type == outputType;  // output y
}

int32_t ConvRotInt8LinearPlugin::configurePlugin(
    nvinfer1::DynamicPluginTensorDesc const* in, int32_t nbInputs,
    nvinfer1::DynamicPluginTensorDesc const* out, int32_t nbOutputs) noexcept {
    (void)out;
    hotstep::diag::log("[ConvRotInt8Linear] configurePlugin ENTER (BUILD phase): "
                     "nbInputs=%d, nbOutputs=%d, group_size=%d, in_features=%d, "
                     "out_features=%d, has_bias=%d, input_dtype=%s, output_dtype=%s\n",
                     nbInputs, nbOutputs,
                     m_group_size, m_in_features, m_out_features, m_has_bias,
                     dtypeNameFromId(m_input_dtype_id), dtypeNameFromId(m_output_dtype_id));
    if (nbInputs < (m_has_bias ? 4 : 3) || nbOutputs < 1) return -1;
    int64_t optM = flattenedRows(in[0].opt);
    int32_t optK = lastDim(in[0].opt);
    if (optM <= 0 || optK <= 0 || optK != m_in_features) return -1;
    if (!validGroupSize(m_group_size, optK)) return -1;
    if (optM > std::numeric_limits<int32_t>::max()) return -1;
    m_M = static_cast<int32_t>(optM);
    m_K = optK;
    m_N = m_out_features;

    // Eagerly initialize the Triton cubin during the build phase so a cubin
    // load failure surfaces as a build-time error with a clear stderr message
    // (via initTriton's diagnostics below), rather than as a runtime assertion
    // inside PluginV3Runner::execute at C:\_src\runtime\gpu\cuda\pluginV3Runner.cpp:252.
    //
    // initTriton() will reject unsupported (group_size, has_bias, input_dtype,
    // output_dtype) combinations with a detailed message explaining which
    // combination was requested and which combinations are in the generated
    // cubin header. The DiT exporter (tools/onnx-export/export_dit.py) emits
    // both FP16 and FP32 plugin boundary dtypes depending on the layer and
    // the HOTSTEP_W8A8_PLUGIN_IO_DTYPE env var, so the cubin header MUST
    // contain both FP16IO and FP32IO variants (see compile_triton_plugin_sm86.py).
    destroyTriton();
    if (!initTriton()) {
        hotstep::diag::log(
                     "[ConvRotInt8Linear] BUILD-TIME FAILURE: initTriton() failed during "
                     "configurePlugin() for group_size=%d, in_features=%d, "
                     "out_features=%d, has_bias=%d, input_dtype=%s, output_dtype=%s. "
                     "See prior stderr for details.\n",
                     m_group_size, m_in_features, m_out_features, m_has_bias,
                     dtypeNameFromId(m_input_dtype_id),
                     dtypeNameFromId(m_output_dtype_id));
        return -1;
    }
    return 0;
}

// Note: destroy() removed in TRT 11; the destructor handles cleanup.

size_t ConvRotInt8LinearPlugin::getWorkspaceSize(
    nvinfer1::DynamicPluginTensorDesc const* inputs, int32_t nbInputs,
    nvinfer1::DynamicPluginTensorDesc const*, int32_t) const noexcept {
    return 0;
}

// ── Custom Tactics (IPluginV3OneBuild) ──────────────────────────────────────

int32_t ConvRotInt8LinearPlugin::getNbTactics() noexcept {
    // Simplest correct sm86-first behavior: advertise exactly one custom tactic
    // that is guaranteed to exist in the generated cubin header. TensorRT still
    // retains implicit default tactic 0.
    return 1;
}

int32_t ConvRotInt8LinearPlugin::getValidTactics(int32_t* tactics, int32_t nbTactics) noexcept {
    if (tactics == nullptr || nbTactics < 1) return 1;
    // TensorRT reserves tactic 0 for the implicit default path; advertised
    // custom tactic IDs must be unique and non-zero.
    // getValidTactics returns an error code, not the number of tactics.
    tactics[0] = 2;  // 128x128 Triton tile
    return 0;
}

char const* ConvRotInt8LinearPlugin::getTimingCacheID() noexcept {
    return "ConvRotInt8Linear.v2";
}

int32_t ConvRotInt8LinearPlugin::getFormatCombinationLimit() noexcept {
    // One physical layout combination today (kLINEAR), with dtype selected by
    // input_dtype/output_dtype. Packed-layout tactics can raise this later
    // without changing the ONNX custom-op schema.
    return 1;
}

char const* ConvRotInt8LinearPlugin::getMetadataString() noexcept {
    // Return a string describing the plugin config (for engine inspector).
    // This is called once; the buffer must live as long as the plugin.
    static thread_local std::string meta;
    std::ostringstream oss;
    oss << "ConvRotInt8Linear.v2(gs=" << m_group_size
        << ",K=" << m_in_features
        << ",N=" << m_out_features
        << ",bias=" << m_has_bias
        << ",in=" << dtypeNameFromId(m_input_dtype_id)
        << ",out=" << dtypeNameFromId(m_output_dtype_id)
        << ",fmt=" << m_preferred_format
        << ",tactic=" << m_tactic << ")";
    meta = oss.str();
    return meta.c_str();
}

// ── IPluginV3OneRuntime ────────────────────────────────────────────────────

int32_t ConvRotInt8LinearPlugin::setTactic(int32_t tactic) noexcept {
    // TensorRT will call this with default tactic 0 or one of the advertised
    // custom tactics. For the current sm86-first implementation, only tactic 2
    // is advertised and both 0 and 2 resolve to the same 128x128 kernel.
    if (tactic != 0 && tactic != 2) {
        hotstep::diag::log("[ConvRotInt8Linear] setTactic(%d) REJECTED — only 0 and 2 are valid.\n",
                         tactic);
        return -1;
    }
    m_tactic = tactic;
    return 0;
}

int32_t ConvRotInt8LinearPlugin::onShapeChange(
    nvinfer1::PluginTensorDesc const* in, int32_t nbInputs,
    nvinfer1::PluginTensorDesc const* out, int32_t nbOutputs) noexcept {
    hotstep::diag::log("[ConvRotInt8Linear] onShapeChange ENTER: nbInputs=%d, nbOutputs=%d, "
                     "serialized(group_size=%d, in_features=%d, out_features=%d, has_bias=%d, "
                     "input_dtype=%s, output_dtype=%s, m_module=%p, m_tactic=%d)\n",
                     nbInputs, nbOutputs,
                     m_group_size, m_in_features, m_out_features, m_has_bias,
                     dtypeNameFromId(m_input_dtype_id), dtypeNameFromId(m_output_dtype_id),
                     m_module, m_tactic);

    if (nbInputs < (m_has_bias ? 4 : 3) || nbOutputs < 1) {
        hotstep::diag::log("[ConvRotInt8Linear] onShapeChange REJECT: nbInputs=%d < required=%d "
                         "OR nbOutputs=%d < 1. m_has_bias=%d.\n",
                         nbInputs, (m_has_bias ? 4 : 3), nbOutputs, m_has_bias);
        return -1;
    }
    // Extract M, K, N from the descriptors.
    (void)out;
    auto const& x_desc = in[0].dims;
    int64_t runtimeM = flattenedRows(x_desc);
    if (runtimeM <= 0 || runtimeM > std::numeric_limits<int32_t>::max()) {
        hotstep::diag::log("[ConvRotInt8Linear] onShapeChange REJECT: runtimeM=%lld is out of "
                         "range (must be in [1, %d]).\n",
                         (long long)runtimeM, std::numeric_limits<int32_t>::max());
        return -1;
    }
    m_M = static_cast<int32_t>(runtimeM);
    m_K = lastDim(x_desc);
    m_N = m_out_features;

    hotstep::diag::log("[ConvRotInt8Linear] onShapeChange shapes: M=%d, K=%d (expected=%d), N=%d, "
                     "x_desc.nbDims=%d, x_desc.d=[",
                     m_M, m_K, m_in_features, m_N, x_desc.nbDims);
    for (int32_t i = 0; i < x_desc.nbDims; ++i) {
        hotstep::diag::log("%s%d", (i ? "," : ""), x_desc.d[i]);
    }
    hotstep::diag::log("]\n");

    if (m_K != m_in_features) {
        hotstep::diag::log("[ConvRotInt8Linear] onShapeChange REJECT: runtime K=%d != serialized "
                         "in_features=%d. The ONNX input shape does not match the build-time "
                         "contract.\n",
                         m_K, m_in_features);
        return -1;
    }
    if (!validGroupSize(m_group_size, m_K)) {
        hotstep::diag::log("[ConvRotInt8Linear] onShapeChange REJECT: group_size=%d not valid "
                         "for K=%d (must divide K evenly, or be 0).\n",
                         m_group_size, m_K);
        return -1;
    }
    if (m_M <= 0 || m_K <= 0 || m_N <= 0) {
        hotstep::diag::log("[ConvRotInt8Linear] onShapeChange REJECT: non-positive dim "
                         "(M=%d, K=%d, N=%d).\n", m_M, m_K, m_N);
        return -1;
    }

    // Initialize Triton compiled kernel lazily for the new shapes/tactics.
    // The cubin is keyed only by (tile, group_size, has_bias, dtype) — not by
    // M/K/N — so we only need to re-init when the previous module is missing
    // (e.g. first call after clone() or destroyTriton()).
    if (!m_module) {
        if (!initTriton()) {
            hotstep::diag::log(
                         "[ConvRotInt8Linear] onShapeChange FAILURE: initTriton() failed for "
                         "group_size=%d, in_features=%d, out_features=%d, has_bias=%d, "
                         "M=%d, K=%d, N=%d, input_dtype=%s, output_dtype=%s.\n",
                         m_group_size, m_in_features, m_out_features, m_has_bias,
                         m_M, m_K, m_N,
                         dtypeNameFromId(m_input_dtype_id),
                         dtypeNameFromId(m_output_dtype_id));
            // Force-flush BEFORE returning the error code — TRT's PluginV3Runner
            // assertion may abort the process before our static destructor runs.
            hotstep::diag::flush();
            return -1;
        }
    } else {
        hotstep::diag::log("[ConvRotInt8Linear] onShapeChange: reusing existing cubin module=%p "
                         "(no re-init needed).\n", m_module);
    }
    hotstep::diag::log("[ConvRotInt8Linear] onShapeChange OK — returning 0.\n");
    return 0;
}

int32_t ConvRotInt8LinearPlugin::enqueue(
    nvinfer1::PluginTensorDesc const* inputDesc,
    nvinfer1::PluginTensorDesc const* outputDesc,
    void const* const* inputs, void* const* outputs,
    void* workspace, cudaStream_t stream) noexcept {
    try {
        (void)inputDesc;
        (void)outputDesc;
        (void)workspace;
        int32_t M = m_M, K = m_K, N = m_N;
        if (M <= 0 || K <= 0 || N <= 0) {
            hotstep::diag::log("[ConvRotInt8Linear] enqueue REJECT: non-positive dim "
                             "(M=%d, K=%d, N=%d) — onShapeChange was not called or failed.\n",
                             M, K, N);
            return -1;
        }

        if (!m_kernelFunc) {
            hotstep::diag::log("[ConvRotInt8Linear] enqueue REJECT: m_kernelFunc=nullptr. "
                             "initTriton() did not run successfully (check log for "
                             "onShapeChange / initTriton errors above).\n");
            return -1;
        }

        hotstep::diag::log("[ConvRotInt8Linear] enqueue ENTER: M=%d, K=%d, N=%d, tactic=%d, "
                         "group_size=%d, has_bias=%d, input_dtype=%s, output_dtype=%s, "
                         "stream=%p, kernelFunc=%p\n",
                         M, K, N, m_tactic, m_group_size, m_has_bias,
                         dtypeNameFromId(m_input_dtype_id), dtypeNameFromId(m_output_dtype_id),
                         (void*)stream, (void*)m_kernelFunc);

        void const* x_ptr      = inputs[0];
        int8_t const* wq_ptr   = static_cast<int8_t const*>(inputs[1]);
        float const* ws_ptr    = static_cast<float const*>(inputs[2]);
        void const* bias_ptr   = m_has_bias ? inputs[3] : nullptr;
        void* y_ptr            = outputs[0];

        hotstep::diag::log("[ConvRotInt8Linear] enqueue ptrs: x=%p, wq=%p, ws=%p, bias=%p, y=%p\n",
                         (void*)x_ptr, (void*)wq_ptr, (void*)ws_ptr, (void*)bias_ptr, (void*)y_ptr);

        // Strides (tensors are row-major kLINEAR format)
        int32_t stride_xm = K;
        int32_t stride_xk = 1;
        int32_t stride_wn = K;
        int32_t stride_wk = 1;
        int32_t stride_ym = N;
        int32_t stride_yn = 1;

        // Block dimensions matching the AOT-compiled cubin. The compile script
        // picks the best (BLOCK_M, BLOCK_N, num_stages) combo per config to
        // maximize pipelining within the device's shared-memory limit. The
        // actual values are baked into the cubin header as _BLOCK_M / _BLOCK_N
        // constants and loaded by initTriton() into m_block_m / m_block_n.
        //
        // M==1 always uses the M1 kernel (BLOCK_M=1). For M>1, BLOCK_M may be
        // 128 (FP16IO / G0 / G64 with ns=3), 64 (G256 FP32IO with ns=2), or
        // 32 (fallback with ns=3). The grid math below handles all cases.
        bool const use_m1_specialized = (M == 1);
        int32_t block_m = use_m1_specialized ? 1 : m_block_m;
        int32_t block_n = use_m1_specialized ? m_block_n : m_block_n;

        // Grid parameters for 1D program tiling in Triton.
        unsigned int gridX = use_m1_specialized
            ? static_cast<unsigned int>((N + block_n - 1) / block_n)
            : static_cast<unsigned int>(((M + block_m - 1) / block_m) * ((N + block_n - 1) / block_n));
        unsigned int gridY = 1;
        unsigned int gridZ = 1;

        // Triton compiled kernels are 1D blocks of num_warps * 32 threads
        unsigned int blockX = 4 * 32; // 128 threads (4 warps)
        unsigned int blockY = 1;
        unsigned int blockZ = 1;

        // Triton compiler automatically appends two global pointer parameters
        // (global scratch / cluster scratch) to every compiled kernel signature.
        // We must provide dummy null pointers for these 2 extra arguments, otherwise
        // cuLaunchKernel reads uninitialized stack memory past args[13] and fails
        // with CUDA_ERROR_INVALID_VALUE (invalid argument).
        void* triton_scratch1 = nullptr;
        void* triton_scratch2 = nullptr;

        // Setup kernel execution arguments (16 args — 14 kernel args + 2 Triton scratch args)
        void* args[] = {
            &x_ptr,
            &wq_ptr,
            &y_ptr,
            &ws_ptr,
            &bias_ptr,
            &M,
            &N,
            &K,
            &stride_xm,
            &stride_xk,
            &stride_wn,
            &stride_wk,
            &stride_ym,
            &stride_yn,
            &triton_scratch1,
            &triton_scratch2
        };

        // Launch the compiled Triton kernel via CUDA Driver API.
        // Modern Triton 3.x uses DYNAMIC shared memory (.extern .shared
        // global_smem[]). We pass m_shared_bytes — the kernel's ACTUAL
        // dynamic shared-memory requirement as reported by Triton's compile
        // metadata and embedded in the cubin header — instead of the device's
        // opt-in ceiling. This is critical: cuLaunchKernel only validates
        //   sharedMemBytes <= cuFuncSetAttribute(MAX_DYNAMIC_SHARED_SIZE_BYTES)
        // and does NOT validate that sharedMemBytes >= the kernel's actual
        // requirement. If we passed a value smaller than the kernel needs
        // (e.g. by passing 0, or by passing a stale value from a header
        // generated before the _SHARED constants existed), cuLaunchKernel
        // would still return CUDA_SUCCESS, but the kernel would fault
        // mid-execution with an out-of-bounds shared memory access —
        // surfaced asynchronously as CUDA_ERROR_ILLEGAL_INSTRUCTION (700)
        // on the next CUDA Driver API call.
        unsigned int const dynamicSmemBytes = static_cast<unsigned int>(m_shared_bytes);
        hotstep::diag::log("[ConvRotInt8Linear] enqueue cuLaunchKernel: kernel=%s, grid=(%u,%u,%u), "
                         "block=(%u,%u,%u), sharedMemBytes=%u (kernel requirement), num_args=16\n",
                         use_m1_specialized ? "fused_convrot_gemm_rowwise_m1_kernel" : "fused_convrot_gemm_rowwise_kernel",
                         gridX, gridY, gridZ, blockX, blockY, blockZ, dynamicSmemBytes);
        CUresult status = cuLaunchKernel(
            static_cast<CUfunction>(m_kernelFunc),
            gridX, gridY, gridZ,
            blockX, blockY, blockZ,
            dynamicSmemBytes, // sharedMemBytes — kernel's actual dynamic shared-mem requirement
            stream,
            args,
            nullptr
        );

        if (status != CUDA_SUCCESS) {
            char const* err_str = "unknown";
            cuGetErrorString(status, &err_str);
            cudaError_t async_status = cudaPeekAtLastError();
            int shared_bytes_static = 0;
            cuFuncGetAttribute(&shared_bytes_static,
                               CU_FUNC_ATTRIBUTE_SHARED_SIZE_BYTES,
                               static_cast<CUfunction>(m_kernelFunc));
            // Also query num_regs and max_threads_per_block — these are the
            // most common reasons for cuLaunchKernel returning CUDA_ERROR_INVALID_VALUE
            // when the cubin compiles but can't be launched on the device.
            int num_regs = 0, max_threads_per_block = 0;
            cuFuncGetAttribute(&num_regs,
                               CU_FUNC_ATTRIBUTE_NUM_REGS,
                               static_cast<CUfunction>(m_kernelFunc));
            cuFuncGetAttribute(&max_threads_per_block,
                               CU_FUNC_ATTRIBUTE_MAX_THREADS_PER_BLOCK,
                               static_cast<CUfunction>(m_kernelFunc));
            hotstep::diag::log(
                         "[ConvRotInt8Linear] enqueue FAILURE: cuLaunchKernel failed: %s "
                         "(code=%d, tactic=%d, group_size=%d, grid=(%u,%u,%u), block=(%u,%u,%u), "
                         "shared_mem_requested=%u, shared_mem_static=%d bytes, num_regs=%d, "
                         "max_threads_per_block=%d, cudaPeekAtLastError=%d (%s), M=%d, K=%d, N=%d, "
                         "input_dtype=%s, output_dtype=%s)\n",
                         err_str, status, m_tactic, m_group_size,
                         gridX, gridY, gridZ,
                         blockX, blockY, blockZ,
                         dynamicSmemBytes, shared_bytes_static, num_regs, max_threads_per_block,
                         static_cast<int>(async_status), cudaGetErrorString(async_status),
                         M, K, N,
                         dtypeNameFromId(m_input_dtype_id),
                         dtypeNameFromId(m_output_dtype_id));
            // Force-flush BEFORE returning the error code — TRT's PluginV3Runner
            // assertion may abort the process before our static destructor runs.
            hotstep::diag::flush();
            return -1;
        }

        hotstep::diag::log("[ConvRotInt8Linear] enqueue OK — cuLaunchKernel returned CUDA_SUCCESS.\n");
        return 0;
    } catch (...) {
        // m_M / m_K / m_N are the cached shape values from onShapeChange().
        // The local M/K/N variables are out of scope here (declared inside the
        // try block above), so use the member fields for the diagnostic message.
        hotstep::diag::log(
                     "[ConvRotInt8Linear] enqueue FAILURE: C++ exception thrown (tactic=%d, "
                     "group_size=%d, M=%d, K=%d, N=%d)\n",
                     m_tactic, m_group_size, m_M, m_K, m_N);
        hotstep::diag::flush();
        return -1;
    }
}

nvinfer1::IPluginV3* ConvRotInt8LinearPlugin::clone() noexcept {
    auto* p = new ConvRotInt8LinearPlugin(m_group_size, m_in_features,
                                          m_out_features, m_has_bias,
                                          m_input_dtype_id, m_output_dtype_id,
                                          m_preferred_format);
    p->m_namespace = m_namespace;
    p->m_tactic = m_tactic;
    return p;
}

nvinfer1::IPluginV3* ConvRotInt8LinearPlugin::attachToContext(
    nvinfer1::IPluginResourceContext* ctx) noexcept {
    // TRT 11 requires this. For our simple plugin that doesn't use
    // plugin resources, just return a clone.
    (void)ctx;
    return clone();
}

nvinfer1::PluginFieldCollection const* ConvRotInt8LinearPlugin::getFieldsToSerialize() noexcept {
    m_fields.clear();
    m_fields.push_back({kFIELD_GROUP_SIZE,   &m_group_size,   nvinfer1::PluginFieldType::kINT32, 1});
    m_fields.push_back({kFIELD_IN_FEATURES,  &m_in_features,  nvinfer1::PluginFieldType::kINT32, 1});
    m_fields.push_back({kFIELD_OUT_FEATURES, &m_out_features, nvinfer1::PluginFieldType::kINT32, 1});
    m_fields.push_back({kFIELD_HAS_BIAS,     &m_has_bias,     nvinfer1::PluginFieldType::kINT32, 1});
    static thread_local std::string input_dtype;
    static thread_local std::string output_dtype;
    input_dtype = dtypeNameFromId(m_input_dtype_id);
    output_dtype = dtypeNameFromId(m_output_dtype_id);
    static thread_local int32_t input_dtype_id;
    static thread_local int32_t output_dtype_id;
    input_dtype_id = m_input_dtype_id;
    output_dtype_id = m_output_dtype_id;
    m_fields.push_back({kFIELD_INPUT_DTYPE,  input_dtype.c_str(),  nvinfer1::PluginFieldType::kCHAR, static_cast<int32_t>(input_dtype.size() + 1)});
    m_fields.push_back({kFIELD_OUTPUT_DTYPE, output_dtype.c_str(), nvinfer1::PluginFieldType::kCHAR, static_cast<int32_t>(output_dtype.size() + 1)});
    m_fields.push_back({kFIELD_INPUT_DTYPE_ID,  &input_dtype_id,  nvinfer1::PluginFieldType::kINT32, 1});
    m_fields.push_back({kFIELD_OUTPUT_DTYPE_ID, &output_dtype_id, nvinfer1::PluginFieldType::kINT32, 1});
    m_fields.push_back({kFIELD_PREFERRED_FORMAT, m_preferred_format.c_str(), nvinfer1::PluginFieldType::kCHAR, static_cast<int32_t>(m_preferred_format.size() + 1)});
    m_fc.nbFields = static_cast<int32_t>(m_fields.size());
    m_fc.fields = m_fields.data();
    return &m_fc;
}

size_t ConvRotInt8LinearPlugin::getSerializationSize() const noexcept {
    return 6 * sizeof(int32_t);  // group_size, in_features, out_features, has_bias, input_dtype_id, output_dtype_id
}

void ConvRotInt8LinearPlugin::serialize(void* buffer) const noexcept {
    uint8_t* d = static_cast<uint8_t*>(buffer);
    std::memcpy(d, &m_group_size,   sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(d, &m_in_features,  sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(d, &m_out_features, sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(d, &m_has_bias,     sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(d, &m_input_dtype_id,  sizeof(int32_t)); d += sizeof(int32_t);
    std::memcpy(d, &m_output_dtype_id, sizeof(int32_t)); d += sizeof(int32_t);
}

// ── Triton / CUDA Driver initialization ─────────────────────────────────────

namespace {

// Compile-time-valid group sizes for the phase-1 butterfly kernel.
// The Triton kernel's _hadamard_butterfly supports exactly these values
// (powers of 4). group_size=0 means no rotation.
bool isValidButterflyGroupSize(int32_t gs) {
    switch (gs) {
        case 0: case 4: case 16: case 64: case 256: case 1024:
            return true;
        default:
            return false;
    }
}

// Map (tile, group_size, has_bias, dtype_suffix) -> compiled cubin payload.
// Returns {nullptr, 0} if no cubin was compiled for this combination.
// IMPORTANT: this switch must stay in lock-step with compile_triton_plugin_sm86.py's
// GROUP_SIZES, BIAS_CONFIGS, and DTYPE_CONFIGS lists. The current sm86-first
// generator emits 128X128 variants for group sizes {0, 64, 256} × {BIAS, NOBIAS}
// × {FP16IO, FP32IO} = 12 cubins total. Do not reference other symbol names
// unless you also regenerate the header with those variants.
struct CubinPayload {
    unsigned char const* data;
    size_t size;
    size_t shared_bytes;  // dynamic shared-mem requirement (Triton metadata.shared)
    int block_m;          // BLOCK_M constexpr baked into the cubin
    int block_n;          // BLOCK_N constexpr baked into the cubin
};

// Lookup helper: expands to a return statement for the matching cubin.
// Naming convention: kCONVROT_INT8_KERNEL_{TILE}_G{GROUP}_{BIAS|NOBIAS}_{DTYPE}
// where DTYPE is FP16IO (FP16 in/out) or FP32IO (FP32 in/out).
//
// The _SHARED constant is emitted by compile_triton_plugin_sm86.py and holds
// the cubin's actual dynamic shared-memory requirement (from Triton's
// metadata.shared). The C++ plugin passes this to cuLaunchKernel instead of
// the device's opt-in ceiling, so the runtime check
//   m_shared_bytes <= getDeviceMaxDynamicSharedMem()
// is a real guard against kernels that were compiled with too many pipeline
// stages for the target device.
//
// The _BLOCK_M and _BLOCK_N constants allow the compile script to pick
// different tile sizes per config (e.g. BLOCK_M=64 for G256 FP32IO to fit
// ns=2 within the 99 KB limit, vs BLOCK_M=128 for G256 FP16IO which fits
// ns=3). The C++ plugin uses these for grid calculation in enqueue().
#define LOOKUP_CUBIN(TILE, GS, BIAS_SUFFIX, DTYPE_SUFFIX) \
    return {kCONVROT_INT8_KERNEL_##TILE##_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX, \
            kCONVROT_INT8_KERNEL_##TILE##_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_SIZE, \
            kCONVROT_INT8_KERNEL_##TILE##_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_SHARED, \
            kCONVROT_INT8_KERNEL_##TILE##_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_BLOCK_M, \
            kCONVROT_INT8_KERNEL_##TILE##_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_BLOCK_N};

// Resolve the dtype suffix from the plugin's input/output dtype ids.
// ONNX TensorProto enum: FLOAT=1, FLOAT16=10, BFLOAT16=16.
// BF16 is not yet supported by the Triton kernel — if requested, we fall
// through to {nullptr, 0} and initTriton() will reject the configuration
// with a clear error message.
char const* dtypeSuffixFor(int32_t input_dtype_id, int32_t output_dtype_id) {
    bool const in_fp16  = (input_dtype_id  == 10);
    bool const out_fp16 = (output_dtype_id == 10);
    if (in_fp16 && out_fp16) {
#if defined(CONVROT_INT8_HAS_DTYPE_FP16IO)
        return "FP16IO";
#else
        return nullptr;
#endif
    }
    if (!in_fp16 && !out_fp16 &&
        (input_dtype_id == 1) && (output_dtype_id == 1)) {
#if defined(CONVROT_INT8_HAS_DTYPE_FP32IO)
        return "FP32IO";
#else
        return nullptr;
#endif
    }
    // Mixed or BF16 — not compiled.
    return nullptr;
}

CubinPayload selectCubin(bool use_64, int32_t group_size, bool has_bias,
                         char const* dtype_suffix) {
    // Keep this in sync with compile_triton_plugin_sm86.py's config lists.
    if (use_64 || dtype_suffix == nullptr) {
        return {nullptr, 0, 0, 0, 0};
    }

    // 128X128 tiles (compiled for sm_86 / RTX 30-series)
    // LOOKUP_CUBIN returns immediately, so no `break` is needed, but they
    // are kept explicit to silence -Wimplicit-fallthrough on compilers that
    // don't see through the macro.
    if (std::strcmp(dtype_suffix, "FP16IO") == 0) {
#if defined(CONVROT_INT8_HAS_DTYPE_FP16IO)
        switch (group_size) {
            case 0:
                if (has_bias) { LOOKUP_CUBIN(128X128, 0, BIAS, FP16IO) }
                else          { LOOKUP_CUBIN(128X128, 0, NOBIAS, FP16IO) }
                break;
            case 64:
                if (has_bias) { LOOKUP_CUBIN(128X128, 64, BIAS, FP16IO) }
                else          { LOOKUP_CUBIN(128X128, 64, NOBIAS, FP16IO) }
                break;
            case 256:
                if (has_bias) { LOOKUP_CUBIN(128X128, 256, BIAS, FP16IO) }
                else          { LOOKUP_CUBIN(128X128, 256, NOBIAS, FP16IO) }
                break;
        }
#endif  // CONVROT_INT8_HAS_DTYPE_FP16IO
    } else if (std::strcmp(dtype_suffix, "FP32IO") == 0) {
#if defined(CONVROT_INT8_HAS_DTYPE_FP32IO)
        switch (group_size) {
            case 0:
                if (has_bias) { LOOKUP_CUBIN(128X128, 0, BIAS, FP32IO) }
                else          { LOOKUP_CUBIN(128X128, 0, NOBIAS, FP32IO) }
                break;
            case 64:
                if (has_bias) { LOOKUP_CUBIN(128X128, 64, BIAS, FP32IO) }
                else          { LOOKUP_CUBIN(128X128, 64, NOBIAS, FP32IO) }
                break;
            case 256:
                if (has_bias) { LOOKUP_CUBIN(128X128, 256, BIAS, FP32IO) }
                else          { LOOKUP_CUBIN(128X128, 256, NOBIAS, FP32IO) }
                break;
        }
#endif  // CONVROT_INT8_HAS_DTYPE_FP32IO
    }
#undef LOOKUP_CUBIN
    return {nullptr, 0, 0, 0, 0};
}


#if defined(CONVROT_INT8_HAS_M1_SPECIALIZED)
#define LOOKUP_M1_CUBIN(GS, BIAS_SUFFIX, DTYPE_SUFFIX) \
    return {kCONVROT_INT8_KERNEL_M1_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX, \
            kCONVROT_INT8_KERNEL_M1_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_SIZE, \
            kCONVROT_INT8_KERNEL_M1_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_SHARED, \
            kCONVROT_INT8_KERNEL_M1_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_BLOCK_M, \
            kCONVROT_INT8_KERNEL_M1_G##GS##_##BIAS_SUFFIX##_##DTYPE_SUFFIX##_BLOCK_N};

CubinPayload selectM1Cubin(int32_t group_size, bool has_bias,
                           char const* dtype_suffix) {
    if (dtype_suffix == nullptr) {
        return {nullptr, 0, 0, 0, 0};
    }
    if (std::strcmp(dtype_suffix, "FP16IO") == 0) {
#if defined(CONVROT_INT8_HAS_DTYPE_FP16IO)
        switch (group_size) {
            case 0:
                if (has_bias) { LOOKUP_M1_CUBIN(0, BIAS, FP16IO) }
                else          { LOOKUP_M1_CUBIN(0, NOBIAS, FP16IO) }
                break;
            case 64:
                if (has_bias) { LOOKUP_M1_CUBIN(64, BIAS, FP16IO) }
                else          { LOOKUP_M1_CUBIN(64, NOBIAS, FP16IO) }
                break;
            case 256:
                if (has_bias) { LOOKUP_M1_CUBIN(256, BIAS, FP16IO) }
                else          { LOOKUP_M1_CUBIN(256, NOBIAS, FP16IO) }
                break;
        }
#endif
    } else if (std::strcmp(dtype_suffix, "FP32IO") == 0) {
#if defined(CONVROT_INT8_HAS_DTYPE_FP32IO)
        switch (group_size) {
            case 0:
                if (has_bias) { LOOKUP_M1_CUBIN(0, BIAS, FP32IO) }
                else          { LOOKUP_M1_CUBIN(0, NOBIAS, FP32IO) }
                break;
            case 64:
                if (has_bias) { LOOKUP_M1_CUBIN(64, BIAS, FP32IO) }
                else          { LOOKUP_M1_CUBIN(64, NOBIAS, FP32IO) }
                break;
            case 256:
                if (has_bias) { LOOKUP_M1_CUBIN(256, BIAS, FP32IO) }
                else          { LOOKUP_M1_CUBIN(256, NOBIAS, FP32IO) }
                break;
        }
#endif
    }
    return {nullptr, 0, 0, 0, 0};
}
#undef LOOKUP_M1_CUBIN
#endif  // CONVROT_INT8_HAS_M1_SPECIALIZED

}  // namespace

bool ConvRotInt8LinearPlugin::initTriton() {
    if (m_module) {
        hotstep::diag::log("[ConvRotInt8Linear] initTriton: m_module already initialized=%p, "
                         "skipping.\n", m_module);
        return true;
    }

    hotstep::diag::log("[ConvRotInt8Linear] initTriton ENTER: group_size=%d, in_features=%d, "
                     "out_features=%d, has_bias=%d, input_dtype=%s (id=%d), output_dtype=%s (id=%d), "
                     "m_tactic=%d\n",
                     m_group_size, m_in_features, m_out_features, m_has_bias,
                     dtypeNameFromId(m_input_dtype_id), m_input_dtype_id,
                     dtypeNameFromId(m_output_dtype_id), m_output_dtype_id,
                     m_tactic);

    // Validate group_size — the butterfly kernel only supports powers of 4.
    if (!isValidButterflyGroupSize(m_group_size)) {
        hotstep::diag::log(
                     "[ConvRotInt8Linear] initTriton REJECT: group_size=%d is not a valid butterfly "
                     "group size (must be 0 or a power of 4: 4, 16, 64, 256, 1024).\n",
                     m_group_size);
        return false;
    }

    // Select the compiled CUBIN payload based on tactic, GROUP_SIZE, HAS_BIAS,
    // and input/output dtype. In the current sm86-first build, both tactic 0
    // and tactic 2 resolve to the same 128x128 kernel inventory.
    bool has_bias = (m_has_bias != 0);
    char const* dtype_suffix = dtypeSuffixFor(m_input_dtype_id, m_output_dtype_id);
    if (dtype_suffix == nullptr) {
        hotstep::diag::log(
                     "[ConvRotInt8Linear] No compiled cubin for input_dtype=%s, "
                     "output_dtype=%s. The Triton kernel only supports FP16-in/FP16-out "
                     "and FP32-in/FP32-out (no mixed or BF16 paths). Re-run "
                     "compile_triton_plugin_sm86.py with the needed DTYPE_CONFIGS entry.\n",
                     dtypeNameFromId(m_input_dtype_id),
                     dtypeNameFromId(m_output_dtype_id));
        return false;
    }
    bool const use_m1_specialized = (m_M == 1);
#if defined(CONVROT_INT8_HAS_M1_SPECIALIZED)
    CubinPayload cubin = use_m1_specialized
        ? selectM1Cubin(m_group_size, has_bias, dtype_suffix)
        : selectCubin(false, m_group_size, has_bias, dtype_suffix);
#else
    CubinPayload cubin = selectCubin(false, m_group_size, has_bias, dtype_suffix);
#endif

    if (cubin.data == nullptr || cubin.size == 0) {
        hotstep::diag::log(
                     "[ConvRotInt8Linear] No compiled cubin for (tactic=%d, tile=%s, "
                     "group_size=%d, has_bias=%d, dtype=%s). The current generated header "
                     "contains 128x128 variants for group sizes {0, 64, 256} × {BIAS, NOBIAS} "
                     "× {FP16IO, FP32IO}; regenerate the Triton cubin header if you need a "
                     "different inventory.\n",
                     m_tactic, use_m1_specialized ? "M1" : "128X128", m_group_size, has_bias, dtype_suffix);
        return false;
    }

    // ── Shared-memory pre-flight check ──────────────────────────────────
    unsigned int const device_max_smem = getDeviceMaxDynamicSharedMem();
    if (cubin.shared_bytes > device_max_smem) {
        hotstep::diag::log(
                     "[ConvRotInt8Linear] initTriton REJECT: cubin requires %zu bytes of dynamic "
                     "shared memory, but device only supports %u bytes (sm_86 opt-in ceiling). "
                     "Re-run compile_triton_plugin_sm86.py to regenerate the header. Config: "
                     "tactic=%d, tile=%s, group_size=%d, has_bias=%d, dtype=%s.\n",
                     cubin.shared_bytes, device_max_smem,
                     m_tactic, use_m1_specialized ? "M1" : "128X128",
                     m_group_size, has_bias, dtype_suffix);
        return false;
    }

    // ── Global module cache lookup ──────────────────────────────────────
    // The cubin data pointer is a stable .rodata address (constexpr array in
    // the cubin header). We use it as a hash key to share the loaded CUmodule
    // across all plugin instances with the same config. This eliminates the
    // 359 × cuModuleLoadData calls per DiT step that were the dominant
    // performance bottleneck (150 s/step → <2 s/step).
    void const* cache_key = cubin.data;
    {
        std::lock_guard<std::mutex> lock(moduleCacheMutex());
        auto it = moduleCache().find(cache_key);
        if (it != moduleCache().end()) {
            // Cache hit — copy the cached handles to this instance. No CUDA
            // Driver API calls, no GPU work. ~200 ns total.
            m_module      = it->second.module;
            m_kernelFunc  = it->second.func;
            m_shared_bytes = it->second.shared_bytes;
            m_block_m     = it->second.block_m;
            m_block_n     = it->second.block_n;
            hotstep::diag::log("[ConvRotInt8Linear] initTriton: cache HIT (key=%p) — "
                             "module=%p, kernelFunc=%p, shared=%zu, block_m=%d, block_n=%d.\n",
                             cache_key, m_module, m_kernelFunc, m_shared_bytes, m_block_m, m_block_n);
            return true;
        }
    }

    // ── Cache miss — load the cubin ─────────────────────────────────────
    cudaError_t preexisting_async_status = cudaPeekAtLastError();
    if (preexisting_async_status != cudaSuccess) {
        hotstep::diag::log(
                     "[ConvRotInt8Linear] WARNING: CUDA runtime already holds error before cuModuleLoadData: %d (%s). "
                     "This strongly suggests a prior kernel triggered a sticky/asynchronous fault.\n",
                     static_cast<int>(preexisting_async_status), cudaGetErrorString(preexisting_async_status));
    }

    CUmodule new_module = nullptr;
    CUresult status = cuModuleLoadData(&new_module, cubin.data);
    if (status != CUDA_SUCCESS) {
        hotstep::diag::log(
                     "[ConvRotInt8Linear] cuModuleLoadData failed: %d (tactic=%d, group_size=%d, "
                     "cubin_size=%zu, shared_required=%zu, cudaPeekAtLastError=%d (%s)).\n",
                     status, m_tactic, m_group_size, cubin.size, cubin.shared_bytes,
                     static_cast<int>(preexisting_async_status), cudaGetErrorString(preexisting_async_status));
        return false;
    }

    char const* kernel_name = use_m1_specialized
        ? "fused_convrot_gemm_rowwise_m1_kernel"
        : "fused_convrot_gemm_rowwise_kernel";
    CUfunction new_func = nullptr;
    status = cuModuleGetFunction(&new_func, new_module, kernel_name);
    if (status != CUDA_SUCCESS) {
        hotstep::diag::log("[ConvRotInt8Linear] cuModuleGetFunction failed: %d\n", status);
        cuModuleUnload(new_module);
        return false;
    }

    // ── Shared-memory opt-in ─────────────────────────────────────────────
    unsigned int const max_dynamic_smem = getDeviceMaxDynamicSharedMem();
    constexpr unsigned int kDefaultSharedMemBytes = 48 * 1024;
    if (max_dynamic_smem > kDefaultSharedMemBytes) {
        status = cuFuncSetAttribute(
            new_func,
            CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES,
            static_cast<int>(max_dynamic_smem));
        if (status != CUDA_SUCCESS) {
            hotstep::diag::log(
                         "[ConvRotInt8Linear] cuFuncSetAttribute(MAX_DYNAMIC_SHARED_SIZE_BYTES=%u) "
                         "failed: %d\n", max_dynamic_smem, status);
            cuModuleUnload(new_module);
            return false;
        }
    }

    // ── Store in cache and in this instance ──────────────────────────────
    m_module      = new_module;
    m_kernelFunc  = new_func;
    m_shared_bytes = cubin.shared_bytes;
    m_block_m     = cubin.block_m;
    m_block_n     = cubin.block_n;

    {
        std::lock_guard<std::mutex> lock(moduleCacheMutex());
        moduleCache()[cache_key] = {new_module, new_func, cubin.shared_bytes,
                                    cubin.block_m, cubin.block_n};
    }

    hotstep::diag::log("[ConvRotInt8Linear] initTriton OK (cache MISS, now cached): module=%p, "
                     "kernelFunc=%p, kernel=%s, shared_required=%zu bytes, block_m=%d, block_n=%d, "
                     "smem_optin_ceiling=%u bytes.\n",
                     m_module, m_kernelFunc, kernel_name, m_shared_bytes,
                     m_block_m, m_block_n, max_dynamic_smem);
    return true;
}

void ConvRotInt8LinearPlugin::destroyTriton() {
    // Do NOT call cuModuleUnload here — the module is shared across all plugin
    // instances via the global module cache. Unloading it would invalidate the
    // handle for every other instance using the same cubin config, causing
    // use-after-free crashes on the next enqueue(). The modules are leaked
    // intentionally at process exit — the CUDA driver reclaims all GPU memory.
    // See the comment above moduleCache() for why static destructor cleanup
    // is unsafe (access violation after CUDA context teardown).
    //
    // We only clear the member pointers so this instance no longer references
    // the shared module. The module stays loaded for reuse by the next clone().
    m_module = nullptr;
    m_kernelFunc = nullptr;
    m_shared_bytes = 0;
    m_block_m = 128;
    m_block_n = 128;
}

// ──────────────────────────────────────────────────────────────────────────
// ConvRotInt8LinearPluginCreator
// ──────────────────────────────────────────────────────────────────────────

ConvRotInt8LinearPluginCreator::ConvRotInt8LinearPluginCreator() {
    m_fields.emplace_back(kFIELD_GROUP_SIZE,   nullptr, nvinfer1::PluginFieldType::kINT32, 1);
    m_fields.emplace_back(kFIELD_IN_FEATURES,  nullptr, nvinfer1::PluginFieldType::kINT32, 1);
    m_fields.emplace_back(kFIELD_OUT_FEATURES, nullptr, nvinfer1::PluginFieldType::kINT32, 1);
    m_fields.emplace_back(kFIELD_HAS_BIAS,     nullptr, nvinfer1::PluginFieldType::kINT32, 1);
    m_fields.emplace_back(kFIELD_INPUT_DTYPE,  nullptr, nvinfer1::PluginFieldType::kCHAR, 0);
    m_fields.emplace_back(kFIELD_OUTPUT_DTYPE, nullptr, nvinfer1::PluginFieldType::kCHAR, 0);
    m_fields.emplace_back(kFIELD_INPUT_DTYPE_ID,  nullptr, nvinfer1::PluginFieldType::kINT32, 1);
    m_fields.emplace_back(kFIELD_OUTPUT_DTYPE_ID, nullptr, nvinfer1::PluginFieldType::kINT32, 1);
    m_fields.emplace_back(kFIELD_PREFERRED_FORMAT, nullptr, nvinfer1::PluginFieldType::kCHAR, 0);
    m_fc.nbFields = static_cast<int32_t>(m_fields.size());
    m_fc.fields = m_fields.data();
}

char const* ConvRotInt8LinearPluginCreator::getPluginName() const noexcept {
    return kCONVROT_INT8_LINEAR_PLUGIN_NAME;
}
char const* ConvRotInt8LinearPluginCreator::getPluginVersion() const noexcept {
    return kCONVROT_INT8_LINEAR_PLUGIN_VERSION;
}
char const* ConvRotInt8LinearPluginCreator::getPluginNamespace() const noexcept {
    return m_namespace.c_str();
}
// Note: setPluginNamespace() removed in TRT 11; namespace set via constructor.
nvinfer1::PluginFieldCollection const* ConvRotInt8LinearPluginCreator::getFieldNames() noexcept {
    return &m_fc;
}

nvinfer1::IPluginV3* ConvRotInt8LinearPluginCreator::createPlugin(
    char const*, nvinfer1::PluginFieldCollection const* fc,
    nvinfer1::TensorRTPhase) noexcept {
    int32_t group_size = 0, in_features = 0, out_features = 0, has_bias = 0;
    int32_t input_dtype_id = 10;
    int32_t output_dtype_id = 10;
    std::string preferred_format = "HWC8";
    for (int32_t i = 0; i < fc->nbFields; ++i) {
        auto const& f = fc->fields[i];
        if (f.name == nullptr || f.data == nullptr) continue;
        if (std::strcmp(f.name, kFIELD_GROUP_SIZE) == 0)
            group_size = *static_cast<int32_t const*>(f.data);
        else if (std::strcmp(f.name, kFIELD_IN_FEATURES) == 0)
            in_features = *static_cast<int32_t const*>(f.data);
        else if (std::strcmp(f.name, kFIELD_OUT_FEATURES) == 0)
            out_features = *static_cast<int32_t const*>(f.data);
        else if (std::strcmp(f.name, kFIELD_HAS_BIAS) == 0)
            has_bias = *static_cast<int32_t const*>(f.data);
        else if (std::strcmp(f.name, kFIELD_INPUT_DTYPE) == 0) {
            if (f.type == nvinfer1::PluginFieldType::kINT32) {
                input_dtype_id = (*static_cast<int32_t const*>(f.data) != 0) ? 10 : 1;
            } else {
                char tmp[16];
                if (readPluginString(f, tmp, sizeof(tmp))) input_dtype_id = parseDtypeId(tmp, input_dtype_id);
            }
        } else if (std::strcmp(f.name, kFIELD_OUTPUT_DTYPE) == 0) {
            if (f.type == nvinfer1::PluginFieldType::kINT32) {
                output_dtype_id = (*static_cast<int32_t const*>(f.data) != 0) ? 10 : 1;
            } else {
                char tmp[16];
                if (readPluginString(f, tmp, sizeof(tmp))) output_dtype_id = parseDtypeId(tmp, output_dtype_id);
            }
        } else if (std::strcmp(f.name, kFIELD_INPUT_DTYPE_ID) == 0) {
            input_dtype_id = normalizeDtypeId(*static_cast<int32_t const*>(f.data), input_dtype_id);
        } else if (std::strcmp(f.name, kFIELD_OUTPUT_DTYPE_ID) == 0) {
            output_dtype_id = normalizeDtypeId(*static_cast<int32_t const*>(f.data), output_dtype_id);
        } else if (std::strcmp(f.name, kFIELD_PREFERRED_FORMAT) == 0) {
            char tmp[32];
            if (readPluginString(f, tmp, sizeof(tmp))) preferred_format = tmp;
        }
    }
    return new ConvRotInt8LinearPlugin(group_size, in_features, out_features, has_bias,
                                       input_dtype_id, output_dtype_id, preferred_format);
}

}  // namespace hotstep

// ──────────────────────────────────────────────────────────────────────────
// Static registration
// ──────────────────────────────────────────────────────────────────────────

// TRT 11: REGISTER_TENSORRT_PLUGIN macro changed and doesn't work
// the same way. Use manual registration via hotstep_register_plugins() below.
// REGISTER_TENSORRT_PLUGIN(hotstep::ConvRotInt8LinearPluginCreator);

// Portable DLL export macro for the plugin entry point.
// On Windows, __declspec(dllexport) is required for GetProcAddress() to find
// the symbol. On Linux/macOS, default visibility is sufficient.
#if defined(_WIN32)
#  define HOTSTEP_PLUGIN_EXPORT __declspec(dllexport)
#else
#  define HOTSTEP_PLUGIN_EXPORT __attribute__((visibility("default")))
#endif

extern "C" {
HOTSTEP_PLUGIN_EXPORT int hotstep_register_plugins() {
    try {
        // ── Cubin header state log ──────────────────────────────────────────
        // Emit the cubin inventory at DLL load time so the user can verify
        // (via hotstep_plugin_diag.log) which dtype variants are actually
        // compiled into the DLL. This catches the common failure mode where
        // the user updated the C++ source but forgot to re-run
        // compile_triton_plugin_sm86.py to regenerate the header with the
        // new DTYPE_CONFIGS — in that case the CONVROT_INT8_HAS_DTYPE_*
        // markers below will be missing and dtypeSuffixFor() will return
        // nullptr for every plugin invocation.
        hotstep::diag::log("=== HotStep plugin DLL loaded ===\n");
        hotstep::diag::log("Cubin header state:\n");
#if defined(CONVROT_INT8_HAS_DTYPE_FP16IO)
        hotstep::diag::log("  CONVROT_INT8_HAS_DTYPE_FP16IO = 1 (FP16-in/FP16-out cubins present)\n");
#else
        hotstep::diag::log("  CONVROT_INT8_HAS_DTYPE_FP16IO = UNDEFINED (no FP16-in/FP16-out cubins)\n");
#endif
#if defined(CONVROT_INT8_HAS_DTYPE_FP32IO)
        hotstep::diag::log("  CONVROT_INT8_HAS_DTYPE_FP32IO = 1 (FP32-in/FP32-out cubins present)\n");
#else
        hotstep::diag::log("  CONVROT_INT8_HAS_DTYPE_FP32IO = UNDEFINED (no FP32-in/FP32-out cubins)\n");
#endif
        hotstep::diag::log("If both are UNDEFINED, you forgot to re-run "
                         "tools/onnx-export/compile_triton_plugin_sm86.py to regenerate "
                         "engine/src/plugins/assets/convrot_int8_kernel_cubin.h after "
                         "updating the C++ plugin source.\n");
        hotstep::diag::log("Log file path: %s (override with HOTSTEP_PLUGIN_LOG env var)\n",
                         hotstep::diag::logPath().c_str());

        // TRT 11: getPluginRegistry() is an extern "C" free function declared
        // in NvInferRuntime.h (included transitively via NvInfer.h).
        // It is in the global namespace, NOT in nvinfer1.
        auto* registry = getPluginRegistry();
        if (!registry) {
            hotstep::diag::log("hotstep_register_plugins: getPluginRegistry() returned null.\n");
            return 1;
        }
        static hotstep::ConvRotInt8LinearPluginCreator creator;
        registry->registerCreator(creator, hotstep::kCONVROT_INT8_LINEAR_PLUGIN_NAMESPACE);
        hotstep::diag::log("hotstep_register_plugins: ConvRotInt8Linear v2 creator registered OK.\n");
        return 0;
    } catch (...) {
        hotstep::diag::log("hotstep_register_plugins: C++ exception thrown during registration.\n");
        return 2;
    }
}
}  // extern "C"

#endif  // HOT_STEP_TRT
