/*
 * convrot_int8_linear_kernel.cu — empty compatibility translation unit.
 *
 * The ConvRot INT8 TensorRT plugin (v13) uses two AOT-compiled Triton kernels:
 *
 *   1. kernel1_convrot_quant — in-register H256 rotation + per-row INT8
 *      activation quantization. X_scale is [M] FP32 (one scale per activation
 *      row, NOT per 256-block).
 *   2. kernel2_gemm_dequant  — explicit-layout Gluon mma_v2 INT8 GEMM with a
 *      persistent cp.async pipeline, single full-K INT32 accumulator, per-row
 *      X_scale × per-row W_scale outer-product FP32 dequant, and optional
 *      bias.  The per-group INT32 fold of v7-v12 is gone.
 *
 * The same two-kernel, autotune-selected Gluon path is used for every runtime
 * M, including M == 1. The previous specialized M1 Triton entry point and the
 * legacy group_size=0 / group_size=256 cubin variants were intentionally
 * removed after profiling and engine-inspector review.
 *
 * The .cubin header is generated by
 * tools/onnx-export/extract_jit_cubins_autotune.py and embedded into
 * engine/src/plugins/assets/convrot_int8_kernel_cubin.h. The plugin loads the
 * cubins at runtime via the CUDA Driver API (cuModuleLoadData +
 * cuModuleGetFunction + cuLaunchKernel) — see convrot_int8_linear_plugin.cpp.
 *
 * This file remains in the build so downstream targets that still list the old
 * CUDA source keep working. If a non-Triton fallback is ever reintroduced, add
 * it here and update the plugin comments/dispatch contract at the same time.
 */

#ifdef HOT_STEP_TRT
// Intentionally empty — runtime kernels are generated from Triton.
#endif
