/*
 * convrot_int8_linear_kernel.cu — empty compatibility translation unit.
 *
 * The ConvRot INT8 TensorRT plugin now uses two AOT-compiled Triton kernels:
 *
 *   1. kernel1_convrot_quant — in-register H_4 butterfly rotation plus
 *      per-K-group dynamic INT8 activation quantization into workspace.
 *   2. kernel2_gemm_dequant  — INT8 GEMM over that workspace with per-group
 *      activation dequantization, per-channel weight scales, and optional bias.
 *
 * The same two-kernel BK64/BM128/BN128 path is used for every runtime M,
 * including M == 1. The previous specialized M1 Triton entry point and the
 * legacy group_size=0 / group_size=256 cubin variants were intentionally
 * removed after profiling and engine-inspector review.
 *
 * The .cubin header is generated by
 * tools/onnx-export/compile_triton_plugin_sm86.py and embedded into
 * engine/src/plugins/assets/convrot_int8_kernel_cubin.h. The plugin loads the
 * cubins at runtime via the CUDA Driver API (cuModuleLoadData +
 * cuModuleGetFunction + cuLaunchKernel) — see convrot_int8_linear_plugin.cpp.
 *
 * This file remains in the build so downstream targets that still list the old
 * CUDA source keep working. If a non-Triton fallback is ever reintroduced, add
 * it here and update the plugin comments/dispatch contract at the same time.
 */

#ifdef HOT_STEP_TRT
// Intentionally empty — runtime kernels are generated from Triton.
#endif
