/*
 * test-convrot-int8-plugin.cpp — unit test for the ConvRotInt8Linear TRT plugin.
 *
 * Validates the C++ plugin kernel against a NumPy reference implementation
 * computed in Python (via a JSON test-vector file). Built by CMake when TRT
 * is enabled; run from the engine build directory.
 *
 * The test exercises three paths:
 *   1. The CUDA kernel directly (launch_convrot_activation_quant +
 *      launch_int8_matmul_dequant_per_row) — verifies the kernel math.
 *   2. The plugin's enqueue() method — verifies the workspace management
 *      and kernel launch wrappers.
 *   3. The plugin creator's createPlugin() — verifies the field-collection
 *      deserialization path the ONNX parser uses.
 *
 * Test vectors are generated by tools/onnx-export/trt_plugins/tests/
 * generate_test_vectors.py and saved as JSON (input tensors + expected
 * output). The test loads the vectors, runs the kernel, and compares.
 *
 * Build: cmake --build . --target test-convrot-int8-plugin
 * Run:   ./test-convrot-int8-plugin <path-to-test-vectors.json>
 */

#ifdef HOT_STEP_TRT

#include "src/plugins/convrot_int8_linear_plugin.h"
#include "src/plugins/convrot_int8_linear_kernel.cuh"

#include <cuda_runtime.h>
#include "NvInfer.h"
#include "NvInferPluginBase.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

// Minimal JSON parser for test vectors. The vector file is generated by
// the Python helper and contains: x, weight_q, weight_scale, H, bias,
// expected_output, group_size, in_features, out_features, has_bias.
// We use a tiny line-based parser (one value per line) to avoid pulling
// a JSON dependency into the test.

namespace {

struct TestVector {
    int32_t M, K, N;          // M=batch, K=in_features, N=out_features
    int32_t group_size;
    int32_t has_bias;
    std::vector<float> x;             // [M*K]
    std::vector<int8_t> weight_q;     // [N*K]
    std::vector<float> weight_scale;  // [N]
    std::vector<float> H;             // [group_size*group_size]
    std::vector<float> bias;          // [N] (empty if !has_bias)
    std::vector<float> expected;      // [M*N]
};

// Helper: CUDA error check macro
#define CUDA_CHECK(call) do {                                            \
    cudaError_t err__ = (call);                                          \
    if (err__ != cudaSuccess) {                                          \
        fprintf(stderr, "CUDA error %s:%d: %s\n", __FILE__, __LINE__,    \
                cudaGetErrorString(err__));                              \
        return false;                                                    \
    }                                                                    \
} while (0)

bool run_kernel_test(const TestVector& tv) {
    // Allocate device buffers
    float*  d_x        = nullptr;
    int8_t* d_wq       = nullptr;
    float*  d_ws       = nullptr;
    float*  d_H        = nullptr;
    float*  d_bias     = nullptr;
    int8_t* d_xq       = nullptr;  // workspace: quantized activations
    float*  d_xs       = nullptr;  // workspace: per-row scale
    float*  d_y        = nullptr;

    size_t x_bytes  = tv.M * tv.K * sizeof(float);
    size_t wq_bytes = tv.N * tv.K * sizeof(int8_t);
    size_t ws_bytes = tv.N * sizeof(float);
    size_t H_bytes  = tv.group_size * tv.group_size * sizeof(float);
    size_t bias_bytes = tv.has_bias ? tv.N * sizeof(float) : 0;
    size_t xq_bytes = tv.M * tv.K * sizeof(int8_t);
    size_t xs_bytes = tv.M * sizeof(float);
    size_t y_bytes  = tv.M * tv.N * sizeof(float);

    CUDA_CHECK(cudaMalloc(&d_x,    x_bytes));
    CUDA_CHECK(cudaMalloc(&d_wq,   wq_bytes));
    CUDA_CHECK(cudaMalloc(&d_ws,   ws_bytes));
    CUDA_CHECK(cudaMalloc(&d_H,    H_bytes));
    if (tv.has_bias) CUDA_CHECK(cudaMalloc(&d_bias, bias_bytes));
    CUDA_CHECK(cudaMalloc(&d_xq,   xq_bytes));
    CUDA_CHECK(cudaMalloc(&d_xs,   xs_bytes));
    CUDA_CHECK(cudaMalloc(&d_y,    y_bytes));

    // Copy inputs to device
    CUDA_CHECK(cudaMemcpy(d_x,  tv.x.data(),           x_bytes,  cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_wq, tv.weight_q.data(),    wq_bytes, cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_ws, tv.weight_scale.data(),ws_bytes, cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_H,  tv.H.data(),           H_bytes,  cudaMemcpyHostToDevice));
    if (tv.has_bias) {
        CUDA_CHECK(cudaMemcpy(d_bias, tv.bias.data(), bias_bytes, cudaMemcpyHostToDevice));
    }

    cudaStream_t stream;
    CUDA_CHECK(cudaStreamCreate(&stream));

    // Phase 1: ConvRot activation quant. The current launcher no longer takes
    // the Hadamard matrix pointer (the regular H4 butterflies are hard-coded in
    // the CUDA kernel) and expects a kernel dtype code: 0=FP32, 1=FP16, 2=BF16.
    if (!hotstep::launch_convrot_activation_quant(
            d_x, d_xq, d_xs, tv.M, tv.K, tv.group_size, /*input_dtype=*/0, stream)) {
        fprintf(stderr, "launch_convrot_activation_quant failed\n");
        return false;
    }

    // Phase 2: INT8 GEMM + dequant + bias
    // NOTE: launch_int8_matmul_dequant_per_row was removed; the GEMM is
    // now handled by cuBLASLt inside the plugin's enqueue() method, and
    // the dequant+bias is done by launch_dequant_bias_epilogue. The
    // standalone kernel test is no longer available; use the plugin
    // enqueue() path instead (see run_plugin_test below).
    // TODO: implement run_plugin_test() that uses the plugin's enqueue().
    CUDA_CHECK(cudaStreamSynchronize(stream));

    // Copy output back
    std::vector<float> actual(tv.M * tv.N);
    CUDA_CHECK(cudaMemcpy(actual.data(), d_y, y_bytes, cudaMemcpyDeviceToHost));

    // Compare against expected
    float max_diff = 0.0f;
    float max_abs_expected = 0.0f;
    for (size_t i = 0; i < actual.size(); ++i) {
        float diff = std::abs(actual[i] - tv.expected[i]);
        if (diff > max_diff) max_diff = diff;
        if (std::abs(tv.expected[i]) > max_abs_expected) {
            max_abs_expected = std::abs(tv.expected[i]);
        }
    }
    // Tolerance: 0.5% of the max expected magnitude, or 1e-3 for near-zero outputs.
    float tolerance = std::max(max_abs_expected * 0.005f, 1e-3f);
    bool pass = max_diff < tolerance;

    if (!pass) {
        fprintf(stderr, "FAIL: max_diff=%f, tolerance=%f, max_abs_expected=%f\n",
                max_diff, tolerance, max_abs_expected);
        // Print first few mismatches
        int shown = 0;
        for (size_t i = 0; i < actual.size() && shown < 5; ++i) {
            if (std::abs(actual[i] - tv.expected[i]) > tolerance) {
                fprintf(stderr, "  [%zu]: actual=%f, expected=%f\n",
                        i, actual[i], tv.expected[i]);
                ++shown;
            }
        }
    } else {
        printf("PASS: max_diff=%f (tolerance=%f)\n", max_diff, tolerance);
    }

    // Cleanup
    cudaFree(d_x);    cudaFree(d_wq);   cudaFree(d_ws);   cudaFree(d_H);
    cudaFree(d_bias); cudaFree(d_xq);   cudaFree(d_xs);   cudaFree(d_y);
    cudaStreamDestroy(stream);
    return pass;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <test-vectors.json>\n", argv[0]);
        return 1;
    }
    // The test vector file is generated by the Python helper at
    // tools/onnx-export/trt_plugins/tests/generate_test_vectors.py.
    // Format: see TestVector struct above.
    //
    // This test is a stub: the actual JSON parsing and kernel invocation
    // live in the implementation. For now we just verify the plugin
    // registers correctly via the C++ creator.
    printf("[ConvRotInt8Linear] Plugin test harness loaded.\n");
    printf("  Plugin name:    %s\n", hotstep::kCONVROT_INT8_LINEAR_PLUGIN_NAME);
    printf("  Plugin version: %s\n", hotstep::kCONVROT_INT8_LINEAR_PLUGIN_VERSION);
    printf("  Plugin namespace: %s\n", hotstep::kCONVROT_INT8_LINEAR_PLUGIN_NAMESPACE);

    // Verify the creator is registered
    // getPluginRegistry() is extern "C" at global scope, not in nvinfer1 namespace.
    auto* registry = getPluginRegistry();
    auto* creator = registry->getCreator(
        hotstep::kCONVROT_INT8_LINEAR_PLUGIN_NAME,
        hotstep::kCONVROT_INT8_LINEAR_PLUGIN_VERSION,
        hotstep::kCONVROT_INT8_LINEAR_PLUGIN_NAMESPACE);
    if (!creator) {
        fprintf(stderr, "FAIL: plugin creator not found in registry\n");
        return 1;
    }
    // getCreator() returns IPluginCreatorInterface* which lacks getPluginName().
    // Cast to IPluginCreatorV3One* to access it.
    auto* v3creator = static_cast<nvinfer1::IPluginCreatorV3One*>(creator);
    printf("  Creator found in registry: %s\n", v3creator->getPluginName());

    // TODO: load test vectors from argv[1] and call run_kernel_test()
    // once the JSON parser is implemented. For now the test passes if
    // the plugin is registered.
    printf("PASS: plugin registration verified\n");
    return 0;
}

#endif  // HOT_STEP_TRT
